In [1]:
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt

# from sqlalchemy import create_engine
# import psycopg2 
# import io

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "last_expr"
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import matplotlib
from IPython.display import display, HTML
from pandas.io.json import json_normalize
from termcolor import colored
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import string
from Demographics_ETL import extract_data, transform_data, load_data

In [2]:
excel_path = 'Excel Files/'

In [3]:
%%HTML
<style type="text/css">

table.dataframe td, table.dataframe th {
    border: 1px  black solid !important;
  color: black !important;
}

</style>

In [4]:
INDEX_NAME='demographics_v1_test'
TYPE_NAME ='_doc' 
uuid = 5100
from elasticsearch import Elasticsearch
#elastic = Elasticsearch(HOST="localhost",PORT=9200)

# elastic = Elasticsearch([{'host':'142.93.213.146','port':9200}])

# <b>Sates List<B>

* Andhra Pradesh
* Arunachal Pradesh
* Assam
* Bihar
* Chhattisgarh
* Goa
* Gujarat
* Haryana
* Himachal Pradesh
* Jammu and Kashmir
* Jharkhand
* Karnataka
* Kerala
* Madhya Pradesh
* Maharashtra
* Manipur
* Meghalaya
* Mizoram
* Nagaland
* Odisha
* Punjab
* Rajasthan
* Sikkim
* Tamil Nadu
* Telangana
* Tripura
* Uttar Pradesh
* Uttarakhand
* West Bengal
* All India

# <b>UT's List<b>

* Andaman and Nicobar Islands
* Chandigarh
* Dadra and Nagar Haveli
* Daman and Diu
* Delhi
* Lakshadweep
* Puducherry

# MNREGA -DISTRICT WISE DATA

In [5]:
main1=pd.read_excel(excel_path + 'mnrega report 2011-12.xlsx')
main1=main1.rename(columns={main1.columns[0]:"StateName"})
main1=main1.rename(columns={main1.columns[1]:"DistrictName"})
main1 = main1.T
main1= main1.rename({"Total households applied for job card":"2012"}, axis='rows') 
# main1

In [6]:
main2=pd.read_excel(excel_path + 'mnrega report 2012-13.xlsx')
main2=main2.rename(columns={main2.columns[0]:"StateName"})
main2=main2.rename(columns={main2.columns[1]:"DistrictName"})
main2 = main2.T
main2= main2.rename({"Total households applied for job card":"2013"}, axis='rows') 
# main2

In [7]:
main3=pd.read_excel(excel_path + 'mnrega report 2013-14.xlsx')
main3=main3.rename(columns={main3.columns[0]:"StateName"})
main3=main3.rename(columns={main3.columns[1]:"DistrictName"})
main3= main3.T
main3= main3.rename({"Total households applied for job card":"2014"}, axis='rows') 
# main3

In [8]:
main4=pd.read_excel(excel_path + 'mnrega report 2014-15.xlsx')
main4=main4.rename(columns={main4.columns[0]:"StateName"})
main4=main4.rename(columns={main4.columns[1]:"DistrictName"})
main4= main4.T
main4= main4.rename({"Total households applied for job card":"2015"}, axis='rows') 
# main4

In [9]:
main5=pd.read_excel(excel_path + 'mnrega report 2015-16.xlsx')
main5=main5.rename(columns={main5.columns[0]:"StateName"})
main5=main5.rename(columns={main5.columns[1]:"DistrictName"})
main5= main5.T
main5= main5.rename({"Total households applied for job card":"2016"}, axis='rows') 
# main5

In [10]:
main6=pd.read_excel(excel_path + 'mnrega report 2016-17.xlsx')
main6=main6.rename(columns={main6.columns[0]:"StateName"})
main6=main6.rename(columns={main6.columns[1]:"DistrictName"})
main6 = main6.T
main6= main6.rename({"Total households applied for job card":"2017"}, axis='rows') 
# main6

In [11]:
main7=pd.read_excel(excel_path + 'mnrega report 2017-18.xlsx')
main7=main7.rename(columns={main7.columns[0]:"StateName"})
main7=main7.rename(columns={main7.columns[1]:"DistrictName"})
main7 = main7.T
main7= main7.rename({"Total households applied for job card":"2018"}, axis='rows') 
# main7

In [12]:
main8=pd.read_excel(excel_path + 'mnrega report 2018-19.xlsx')
main8=main8.rename(columns={main8.columns[0]:"StateName"})
main8=main8.rename(columns={main8.columns[1]:"DistrictName"})
main8= main8.T
main8= main8.rename({"Total households applied for job card":"2019"}, axis='rows') 
# main8

In [13]:
# district_list= main8.DistrictName.unique()
# district_list=district_list.tolist()
# district_list

In [14]:
main9=pd.read_excel(excel_path + 'mnrega report 2019-20.xlsx')
main9=main9.rename(columns={main9.columns[0]:"StateName"})
main9=main9.rename(columns={main9.columns[1]:"DistrictName"})
main9 = main9.T
main9= main9.rename({"Total households applied for job card":"2020"}, axis='rows') 
# main9

In [15]:
main10=pd.read_excel(excel_path + 'mnrega report 2020-21.xlsx')
main10=main10.rename(columns={main10.columns[0]:"StateName"})
main10=main10.rename(columns={main10.columns[1]:"DistrictName"})
main10 = main10.T
main10= main10.rename({"Total households applied for job card":"2021"}, axis='rows') 
# main10

In [16]:
# main10.DistrictName.unique()

In [17]:
main_df = main1.append([main2,main3,main4,main5,main6,main7,main8,main9,main10])
main_df = main_df.reset_index()
main_df = main_df.drop([3,4,6,7,9,10,12,13,15,16,18,19,21,22,24,25,27,28])
main_df=main_df.rename(columns={main_df.columns[0]:""})
main_df.set_index("",inplace=True)
main_df = main_df.T
main_df

                StateName               DistrictName       2012       2013       2014       2015       2016       2017       2018       2019    2020    2021
0     ANDAMAN AND NICOBAR                   NICOBARS       2882       5149       5512       5649       5746       5667       5578       5703    5721    5721
1     ANDAMAN AND NICOBAR   NORTH AND MIDDLE ANDAMAN      17687      18292      19765      20587      20949      20217      19800      19595   18420   17471
2     ANDAMAN AND NICOBAR              SOUTH ANDAMAN      24827      25048      25374      25165      25144      10496       9940       9562    9397    9235
3    DADRA & NAGAR HAVELI     DADRA AND NAGAR HAVELI       7845       8176       8157       8157       8157       8157       9141          0  835676  872051
4             DAMAN & DIU                      DAMAN          0          0          0          0          0          0          0          0  691661  719650
..                    ...                        ...        ...        ...        ...        ...        ...        ...        ...        ...     ...     ...
705           WEST BENGAL          PASCHIM MEDINIPUR     874923     898113     921649     944010     964128     976011     726728     736253     NaN     NaN
706           WEST BENGAL            PURBA MEDINIPUR     670770     685931     707296     727831     742591     758838     773259     782936     NaN     NaN
707           WEST BENGAL                    PURULIA     446947     456861     469053     479954     488525     497750     499683     505141     NaN     NaN
708           WEST BENGAL  SILIGURI MAHAKUMA PARISAD      86873      91666      96178      99874     101770     104666      96516      97452     NaN     NaN
709                 Total                          0  122641399  127736953  125447824  124489895  127746183  125598201  126282744  129653358     NaN     NaN

[710 rows x 12 columns]

### state's list for data frames

In [18]:
states_list=main_df.StateName.unique()
states_list=states_list.tolist()
states_list

['ANDAMAN AND NICOBAR',
 'DADRA & NAGAR HAVELI',
 'DAMAN & DIU',
 'LAKSHADWEEP',
 'NAGALAND',
 'ANDHRA PRADESH',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'BIHAR',
 'CHHATTISGARH',
 'GOA',
 'GUJARAT',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU AND KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'ODISHA',
 'PUDUCHERRY',
 'PUNJAB',
 'RAJASTHAN',
 'SIKKIM',
 'TAMIL NADU',
 'TRIPURA',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL',
 'Total']

In [19]:

# statedic = {}
# for i in range(len(states_list)):
#         j = states_list[i]
#         statedic[states_list[i]] = pd.DataFrame(main_df.loc[main_df['StateName'] == j ])

In [20]:
# dfdic = {}

# for i in range(len(states_list)):
#     df = statedic[states_list[i]]
#     df = df.drop(columns=df.columns[0])
#     df = df.rename(columns={df.columns[0]:"Year"})
#     df.set_index('Year',inplace=True)
#     df = df.T
#     df = df.loc[:,~df.columns.duplicated()]
#     df.columns = df.columns.astype(str)
#     df.columns = df.columns.str.title()
#     dfdic[states_list[i]]=df

In [21]:
statedic = {}
for i in range(len(states_list)):
        j = states_list[i]
        df = pd.DataFrame(main_df.loc[main_df['StateName'] == j ])
        df = df.drop(columns=df.columns[0])
        df = df.rename(columns={df.columns[0]:"Year"})
        df.set_index('Year',inplace=True)
        df = df.T
        df = df.loc[:,~df.columns.duplicated()]
        df = df.replace(np.nan, '', regex=True)
        df.columns = df.columns.astype(str)
        df.columns = df.columns.str.title()
        statedic[states_list[i]]=df

In [22]:
PATH = 'Schemes/MNREGA/Total households applied for job card/'

## Andaman and Nicobar Islands

In [23]:
andaman = statedic[states_list[0]]
andaman

Year Nicobars North And Middle Andaman South Andaman

2012     2882                    17687         24827
2013     5149                    18292         25048
2014     5512                    19765         25374
2015     5649                    20587         25165
2016     5746                    20949         25144
2017     5667                    20217         10496
2018     5578                    19800          9940
2019     5703                    19595          9562
2020     5721                    18420          9397
2021     5721                    17471          9235

In [24]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Andaman and Nicobar Islands"
    
}

In [25]:
andaman_meta = transform_data(andaman,doc_source)
andaman_meta

Year                                                 Nicobars                           North And Middle Andaman                                      South Andaman
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District
State                             Andaman and Nicobar Islands                        Andaman and Nicobar Islands                        Andaman and Nicobar Islands

In [26]:
uuid = load_data(andaman,andaman_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5100
uuid is 5101
uuid is 5102

## Dadra and Nagar Haveli

In [27]:
Dadra_and_Nagar_Haveli = statedic[states_list[1]]
Dadra_and_Nagar_Haveli

Year Dadra And Nagar Haveli

2012                   7845
2013                   8176
2014                   8157
2015                   8157
2016                   8157
2017                   8157
2018                   9141
2019                      0
2020                 835676
2021                 872051

In [28]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Dadra and Nagar Haveli"
    
}
Dadra_and_Nagar_Haveli_meta = transform_data(Dadra_and_Nagar_Haveli,doc_source)
Dadra_and_Nagar_Haveli_meta

Year                                   Dadra And Nagar Haveli
Doc_Source                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People
Mode                                                 District
State                                  Dadra and Nagar Haveli

In [29]:
uuid = load_data(Dadra_and_Nagar_Haveli,Dadra_and_Nagar_Haveli_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5103

## Daman and Diu

In [30]:
Daman_and_Diu = statedic[states_list[2]]
Daman_and_Diu

Year   Daman     Diu

2012       0       0
2013       0       0
2014       0       0
2015       0       0
2016       0       0
2017       0       0
2018       0       0
2019       0       0
2020  691661  555102
2021  719650  573102

In [31]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Daman and Diu"
    
}
Daman_and_Diu_meta = transform_data(Daman_and_Diu,doc_source)
Daman_and_Diu_meta

Year                                                    Daman                                                Diu
Doc_Source                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People
Mode                                                 District                                           District
State                                           Daman and Diu                                      Daman and Diu

In [32]:
uuid = load_data(Daman_and_Diu,Daman_and_Diu_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5104
uuid is 5105

## Lakshadweep

In [33]:
Lakshadweep = statedic[states_list[3]]
Lakshadweep

Year Lakshadweep District

2012                 8254
2013                 8493
2014                 8709
2015                 8452
2016                 8309
2017                 8243
2018                 8178
2019                    0
2020               858244
2021               886044

In [34]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Lakshadweep"
    
}
Lakshadweep_meta = transform_data(Lakshadweep,doc_source)
Lakshadweep_meta

Year                                     Lakshadweep District
Doc_Source                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People
Mode                                                 District
State                                             Lakshadweep

In [35]:
uuid = load_data(Lakshadweep,Lakshadweep_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5106

## Nagaland

In [36]:
Nagaland = statedic[states_list[4]]
Nagaland

Year Dimapur Kiphire  Kohima Longleng Mokokchung     Mon   Peren    Phek Tuensang  Wokha Zunheboto

2012   58125   20980   58703    21175      32404   36983   23069   30979    39515  26874     35671
2013   64925   21412   55496    21276      33074   37106   24012   32442    44587  26878     36827
2014   68438   23483   54551    21157      34413   37160   24513   33946    45232  33371     37361
2015   69841   23483   54402    21156      35533   37459   25765   33763    47234  37985     37409
2016   70228   23483   53466    21156      35734   37656   25765   33832    48527  37981     37555
2017   72000   23528   53509    21773      35705   38468   25763   33829    48554  38400     37686
2018   72897   23528   53953    21422      35590   39721   26692   34045    48554  38556     37686
2019       0       0       0        0          0       0       0       0        0      0         0
2020  809435  641688  831642   607772     761015  594952  496468  518727   759912   8688     14527
2021  827290  659373  848821   617797     794911  616664  542259  546380   780847   8917     14318

In [37]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Nagaland"
    
}
Nagaland_meta = transform_data(Nagaland,doc_source)
Nagaland_meta

Year                                                  Dimapur                                            Kiphire                                             Kohima                                           Longleng                                         Mokokchung                                                Mon                                              Peren                                               Phek                                           Tuensang                                              Wokha                                          Zunheboto
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                                Nagaland                                           Nagaland                                           Nagaland                                           Nagaland                                           Nagaland                                           Nagaland                                           Nagaland                                           Nagaland                                           Nagaland                                           Nagaland                                           Nagaland

In [38]:
uuid = load_data(Nagaland,Nagaland_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5107
uuid is 5108
uuid is 5109
uuid is 5110
uuid is 5111
uuid is 5112
uuid is 5113
uuid is 5114
uuid is 5115
uuid is 5116
uuid is 5117

## Andhra Pradesh

In [39]:
Andhra_Pradesh = statedic[states_list[5]]
Andhra_Pradesh

Year Anantapur Chittoor Cuddapah East Godavari  Guntur Krishna Kurnool Nellore Prakasam Srikakulam Visakhapatanam Vizianagaram West Godavari

2012    784970   606563   502095        802422  550455  468300  688862  468880   543040     533783         458135       508111        250854
2013    854844   689683   584341        897788  678967  545666  780740  529410   676081     604040         549980       564637        568049
2014    872025   703574   601583        947416  717481  574419  800939  551773   722932     637902         570073       588278        595465
2015    785003   654862   558165        771110  728570  579579  745013  563900   697508     561996         472167       543981        620304
2016    796804   656524   564970        776137  756146  589097  767182  574083   726045     565785         473705       541369        653813
2017    795844   667913   564721        800901  782077  605090  768430  590851   728978     568351         472841       511486        696901
2018    792459   672107   557000        822041  782805  614942  783856  589038   738130     568331         481753       509958        728831
2019    807803   683472   549171        841970  799867  633643  811609  601664   749945     583331         490649       515104        748063
2020     24514     9431    16630          5172    7831   14921   19488    8409     9736       3101           5412        16729          9787
2021     28081     9633    16447          5222    8086   15005   19373    8445     9833       3066           5412        17913         10252

In [40]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Andhra Pradesh"
    
}
Andhra_Pradesh_meta = transform_data(Andhra_Pradesh,doc_source)
Andhra_Pradesh_meta

Year                                                Anantapur                                           Chittoor                                           Cuddapah                                      East Godavari                                             Guntur                                            Krishna                                            Kurnool                                            Nellore                                           Prakasam                                         Srikakulam                                     Visakhapatanam                                       Vizianagaram                                      West Godavari
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                          Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh                                     Andhra Pradesh

In [41]:
uuid = load_data(Andhra_Pradesh,Andhra_Pradesh_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5118
uuid is 5119
uuid is 5120
uuid is 5121
uuid is 5122
uuid is 5123
uuid is 5124
uuid is 5125
uuid is 5126
uuid is 5127
uuid is 5128
uuid is 5129
uuid is 5130

## Arunachal Pradesh

In [42]:
Arunachal_Pradesh = statedic[states_list[6]]
Arunachal_Pradesh

Year  Anjaw Changlang East Kameng East Siang Kurung Kumey   Lohit Lower Dibang Valley Lower Subansiri Papum Pare  Tawang  Tirap Upper Dibang Valley Upper Siang Upper Subansiri West Kameng West Siang

2012   4518     11856       14963       9916        13924   15621                6046           18516      12182    7332  10187                1379          48           15343        9487      12656
2013   4535     12129       15014      10045        15631   16459                6368           19113      12995    7558  16319                1661        4501           15701        9592      13917
2014   6394     12209       15594      10583        19934   17414                6799           19140      14323    7610  16615                1901        4658           15787        9887      14305
2015   7110     12351       16849       8408        21879   18230                6965           19541      14691    7835   8762                2066        4830           16200       10038      12090
2016   7295     12722       16923       8696        11437   18330                7103           21152      16647    8077   8850                2424        4972           16672       10201      12200
2017   7315     12799       20302       8593        12284    4983                6979           21211      17021    7985   8865                2775        5044           17337       10377      13374
2018   7285     13382       20835       8946        13372    4945                7391           20974      16642    8090   8875                2828        5121           17841        9615      14068
2019   7414     13947       20974       8972        15908    5133                7476           21222      17708    8233   9239                2898        5186           19132        8706      14688
2020  11749    241112      304366     123158       278767  113055              164400          157503     211965  191003  33951              155857      183696          124042      144084     277516
2021  11892    240318      308804     124240       279237  113256              166298          160248     216242  191238  33981              158437      186061          124688      146052     283116

In [43]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Arunachal Pradesh"
    
}
Arunachal_Pradesh_meta = transform_data(Arunachal_Pradesh,doc_source)
Arunachal_Pradesh_meta

Year                                                    Anjaw                                          Changlang                                        East Kameng                                         East Siang                                       Kurung Kumey                                              Lohit                                Lower Dibang Valley                                    Lower Subansiri                                         Papum Pare                                             Tawang                                              Tirap                                Upper Dibang Valley                                        Upper Siang                                    Upper Subansiri                                        West Kameng                                         West Siang
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                       Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh                                  Arunachal Pradesh

In [44]:
uuid = load_data(Arunachal_Pradesh,Arunachal_Pradesh_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5131
uuid is 5132
uuid is 5133
uuid is 5134
uuid is 5135
uuid is 5136
uuid is 5137
uuid is 5138
uuid is 5139
uuid is 5140
uuid is 5141
uuid is 5142
uuid is 5143
uuid is 5144
uuid is 5145
uuid is 5146

## Assam

In [45]:
Assam = statedic[states_list[7]]
Assam

Year   Baksa Barpeta Bongaigaon  Cachar Chirang Darrang Dhemaji  Dhubri Dibrugarh Dima Hasao Goalpara Golaghat Hailakandi  Jorhat  Kamrup Kamrup (Metro) Karbi Anglong Karimganj Kokrajhar Lakhimpur Morigaon  Nagaon Nalbari Sivasagar Sonitpur Tinsukia Udalguri

2012  175671  251125     114896  190616  108356  150643  119050  193297    122158      39750   154274   130119     120578  103386  196332          37197        204600    175235    179390    166915   134041  210264  104016    111954   222720   115355   117649
2013  184563  249806     115035  200247  108572  150405  117412  193623    132557      39785   147019   130823     118866  106776  196607          37332        209834    175940    180759    164055   157823  217766  106382    122714   230457   117574   118688
2014  188439  249634     115580  210399   92523  153266  119606  199625    148090      40276   146975   135533     116484  126104  197669          37586        216371    174598    180725    166082   172398  235154  111240    143931   242576   125037   119459
2015  205226  261967     117247  274738   96784  167842  138474  209442    154818      40606   150007   145422     119696  134811  204006          40155        226277    197979    212920    171329   187650  279515  116069    150674   254542   132783   122452
2016  248003  273945     122051  281934  109063  173813  167686  225195    162669      41436   154115   161013     120456  159226  223329          41354        232218    213438    261820    179532   192959  329042  121196    155695   278809   143709   144971
2017  227032  277095     109846  247218  111000  149844  110741  182067    163702      29794   137388   159463     119903  160178  235254          42360        174361    235325    185146    178315   159447  213844  118344     99766   153471   137028   157463
2018  218094  288110     113531  230497  113445  154164  128169  187290    169825      31759   145004   165802     118383  129875  252070          43548        141655    200331    187597    185719   167460  228722  131236    103460   152555   145505   165057
2019  232368  290457     118717  261440  111116  158319  150252  198927    179599      32906   149090   171747     121314  135143  261466          44054        152728    212728    192984    201214   172625  245837  148361    106389   160185   153825   169998
2020   44963  162491     218648  198691  216088  177375  264880  151843    112529     182746   169851   178843     621711  138640  438991         413471        457190    546072    448640    304772   771196  763237  376587    361181   178012   260000   648873
2021   45425  164027     221196  199293  219298  179824  268604  152435    113546     187210   173714   178797     648011  147499  459786         441871        480468    566911    473566    316853   838917  798850  390865    374305   185078   279715   671126

In [46]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Assam"
    
}
Assam_meta = transform_data(Assam,doc_source)
Assam_meta

Year,Baksa,Barpeta,Bongaigaon,Cachar,Chirang,Darrang,Dhemaji,Dhubri,Dibrugarh,Dima Hasao,Goalpara,Golaghat,Hailakandi,Jorhat,Kamrup,Kamrup (Metro),Karbi Anglong,Karimganj,Kokrajhar,Lakhimpur,Morigaon,Nagaon,Nalbari,Sivasagar,Sonitpur,Tinsukia,Udalguri
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam,Assam

In [47]:
uuid = load_data(Assam,Assam_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5147
uuid is 5148
uuid is 5149
uuid is 5150
uuid is 5151
uuid is 5152
uuid is 5153
uuid is 5154
uuid is 5155
uuid is 5156
uuid is 5157
uuid is 5158
uuid is 5159
uuid is 5160
uuid is 5161
uuid is 5162
uuid is 5163
uuid is 5164
uuid is 5165
uuid is 5166
uuid is 5167
uuid is 5168
uuid is 5169
uuid is 5170
uuid is 5171
uuid is 5172
uuid is 5173

## Bihar

In [48]:
Bihar = statedic[states_list[8]]
Bihar

Year  Araria   Arwal Auranagabad   Banka Begusarai Bhagalpur Bhojpur   Buxar Darbhanga    Gaya Gopalganj   Jamui Jehanabad Kaimur (Bhabua) Katihar Khagaria Kishanganj Lakhisarai Madhepura Madhubani  Munger Muzaffarpur Nalanda  Nawada Pashchim Champaran   Patna Purbi Champaran  Purnia  Rohtas Saharsa Samastipur   Saran Sheikhpura Sheohar Sitamarhi   Siwan  Supaul Vaishali

2012  386267   88689      317300  256578    310266    415165  408810  238186    473055  479125    321662  227657    133544          187559  388345   182812     245789     144781    303201    524957  177747      642606  395736  323262             409257  492777          578109  389231  326185  298330     441265  467405      87065   86061    393584  370115  287736   498485
2013  395471   91680      324183  263996    318491    433876  424652  245981    479054  567671    336485  242798    137307          195746  399210   186214     254507     150100    309999    549011  180198      671176  414641  336675             434699  518110          600351  413216  344492  305914     457833  481763      93577   89344    412813  377469  293212   510427
2014  394779   91575      324754  265962    314816    414109  431098  236661    483397  608743    350281  247174    135910          199102  436343   184588     255212     148868    306201    562083  180454      638615  399215  365418             444253  505222          600842  422766  350301  314943     450854  477594      92787   80987    432937  343493  291868   511850
2015  419537   96028      333341  269756    310157    390786  332012  238504    486767  547266    345253  247004    136746          206706  461662   170354     241819     150422    302502    512994  177892      600776  392697  390866             450147  507907          607998  433998  351277  326516     459803  466986      93573   81314    434056  292112  304610   521222
2016  447413  103160      350783  296882    338023    425869  353143  273714    512482  584308    359173  268700    147444          217974  491720   193140     256975     163805    353940    538711  188313      616607  422268  431661             466203  536571          642122  473592  366016  352590     503458  493862     102419   90903    452944  308708  322442   558558
2017  487055  122108      373502  320328    362355    454169  385843  294432    565273  630066    366997  297709    157626          231818  546045   217283     274906     182751    389663    577613  204440      658978  453249  470245             508423  595162          693526  517512  379616  398616     561249  551010     102801   98573    485551  322111  352146   626309
2018  513011  116648      393276  346827    381057    469988  387496  288046    616364  674248    351402  315167    160589          236441  578526   234673     283347     194127    408543    605430  217049      681796  455034  487500             541376  618797          727075  545685  387737  423052     615737  568090     108001   95766    534895  324390  361150   647977
2019  568012  127764      416025  372124    410127    515115  406992  294659    692550  711341    358951  338560    171632          248085  609804   261147     293497     205889    431680    655789  230932      730694  466402  508064             561787  645520          786039  587101  404245  446461     684749  628818     111735  108181    583875  339008  388808   710750
2020  286492  311660      211741  461036    713292    247038  781201  487804    527522  607968    697797  852255    618529          424832  469250   782119     683932     120078    119195    631035  359421      414470  753821  151329             224297  123061          106281  166986   37370  255271      39373  154490     112407  138716    281373  160920  143687   172621
2021  301400  323555      217893  471365    758376    258132  813234  510124    539250  657867    741849  906103    642131          459297  477911   847244     719077     125727    129454    668655  386694      428822  792673  153667             241946  122782          113983  176563   42146  214322      39704  157610     119558  142121    299567  162656  145649   181075

In [49]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Bihar"
    
}
Bihar_meta = transform_data(Bihar,doc_source)
Bihar_meta

Year,Araria,Arwal,Auranagabad,Banka,Begusarai,Bhagalpur,Bhojpur,Buxar,Darbhanga,Gaya,Gopalganj,Jamui,Jehanabad,Kaimur (Bhabua),Katihar,Khagaria,Kishanganj,Lakhisarai,Madhepura,Madhubani,Munger,Muzaffarpur,Nalanda,Nawada,Pashchim Champaran,Patna,Purbi Champaran,Purnia,Rohtas,Saharsa,Samastipur,Saran,Sheikhpura,Sheohar,Sitamarhi,Siwan,Supaul,Vaishali
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar,Bihar

In [50]:
uuid = load_data(Bihar,Bihar_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5174
uuid is 5175
uuid is 5176
uuid is 5177
uuid is 5178
uuid is 5179
uuid is 5180
uuid is 5181
uuid is 5182
uuid is 5183
uuid is 5184
uuid is 5185
uuid is 5186
uuid is 5187
uuid is 5188
uuid is 5189
uuid is 5190
uuid is 5191
uuid is 5192
uuid is 5193
uuid is 5194
uuid is 5195
uuid is 5196
uuid is 5197
uuid is 5198
uuid is 5199
uuid is 5200
uuid is 5201
uuid is 5202
uuid is 5203
uuid is 5204
uuid is 5205
uuid is 5206
uuid is 5207
uuid is 5208
uuid is 5209
uuid is 5210
uuid is 5211

## Chhattisgarh

In [51]:
Chhattisgarh = statedic[states_list[9]]
Chhattisgarh

Year   Balod Baloda Bazar Balrampur  Bastar Bemetara Bijapur Bilaspur Dantewada Dhamtari    Durg Gariyaband Janjgir-Champa Jashpur  Kanker Kawardha Kondagaon   Korba   Korea Mahasamund Mungeli Narayanpur Raigarh  Raipur Rajnandagon  Sukma Surajpur Surguja

2012       0            0         0  231054        0   56719   456889    101061   155819  409104          0         267752  201969  186413   223210         0  182422  116952     228190       0      21497  245578  529758      330226      0        0  457751
2013  152280       261717    152571  123785   162719   59371   282901     49489   159560  105922     145131         299706  199786  191736   196106    102709  190033  120907     234338  156713      18796  251543  157478      331352  51673   149217  150693
2014  151850       224430    131002  112205   158529   55711   266981     47447   155325  106666     136188         267634  166891  161077   153322     98427  180532  111156     224578  155037      20155  244505  136900      288666  50811   132743  119820
2015  152304       226151    136320  106911   159177   57263   263556     47245   151371  107658     136645         247983  165174  160682   151032     96444  187522   98059     220669  154631      20049  242193  142853      291177  50181   134699  120339
2016  153527       230651    136507  111120   163521   50867   250139     47024   151792  107596     131443         256256  162573  157929   158582     96984  189036  106664     211804  155689      21055  208262  142601      290238  49691   133611  122948
2017  149036       230330    124838  113870   155934   33590   229032     36594   148579  103263     130181         236011  155665  141115   160255     91933  180343  102076     199629  130431      21100  204013  144233      241427  41154   129346  142213
2018  153003       238851    125772  114134   160056   33564   232610     38065   150543  106919     132432         265185  156666  142992   163076     95845  132999  107538     204924  120817      21607  220595  147391      254585  44427   145381  123197
2019  154133       226905    130373  102102   161286   34443   243923     38568   152751  109361     136650         277030  159067  144138   168172     97346  139553  111916     209244  127410      22223  227861  150584      262132  52476   148606  133561
2020   98365       145900    110893  211787   135478   22534   237624    151319   264056   54111     150069         140413   14259       0        0     19372   17737  123531     101657  193268     156543  114162   70273       47864  46647   420289   42377
2021   99089       145358    114236  216425   141864   22934   249715    164562   271326   54137     148991         143829   14327       0        0     19405   17759  126442     107218  196063     161837  116015   96602       52653  46383   449885   43165

In [52]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Chhattisgarh"
    
}
Chhattisgarh_meta = transform_data(Chhattisgarh,doc_source)
Chhattisgarh_meta

Year,Balod,Baloda Bazar,Balrampur,Bastar,Bemetara,Bijapur,Bilaspur,Dantewada,Dhamtari,Durg,Gariyaband,Janjgir-Champa,Jashpur,Kanker,Kawardha,Kondagaon,Korba,Korea,Mahasamund,Mungeli,Narayanpur,Raigarh,Raipur,Rajnandagon,Sukma,Surajpur,Surguja
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh,Chhattisgarh

In [53]:
uuid = load_data(Chhattisgarh,Chhattisgarh_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5212
uuid is 5213
uuid is 5214
uuid is 5215
uuid is 5216
uuid is 5217
uuid is 5218
uuid is 5219
uuid is 5220
uuid is 5221
uuid is 5222
uuid is 5223
uuid is 5224
uuid is 5225
uuid is 5226
uuid is 5227
uuid is 5228
uuid is 5229
uuid is 5230
uuid is 5231
uuid is 5232
uuid is 5233
uuid is 5234
uuid is 5235
uuid is 5236
uuid is 5237
uuid is 5238

## Goa

In [54]:
Goa = statedic[states_list[10]]
Goa

Year North Goa South Goa

2012     19615     13001
2013     19910     13104
2014     20554     13315
2015     21210     13556
2016     21889     13796
2017     18793     17387
2018     19191     17630
2019     19250     17700
2020    109466     26872
2021    110441     30513

In [55]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Goa"
    
}
Goa_meta = transform_data(Goa,doc_source)
Goa_meta

Year                                                North Goa                                          South Goa
Doc_Source                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People
Mode                                                 District                                           District
State                                                     Goa                                                Goa

In [56]:
uuid = load_data(Goa,Goa_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5239
uuid is 5240

## Gujarat

In [57]:
Gujarat = statedic[states_list[11]]
Gujarat

Year Ahmadabad  Amreli   Anand Banas Kantha Bharuch Bhavnagar  Botad   Dang   Dohad Gandhinagar Jamnagar Junagadh Kachchh   Kheda Mahesana  Morbi Narmada Navsari Panch Mahals   Patan Porbandar  Rajkot Sabar Kantha   Surat Surendranagar    Tapi Vadodara  Valsad

2012    143095  118972  149215       304128  126349     99613      0  46278  329432       50253    79764   162823  133233  184307    70132      0  104145  115296       355171  197056     37734  155447       216723  136599        172999  153102   257507  185580
2013    131172  120552  138479       283482  125120     95734      0  46234  266274       47752    78736   175214   95963  176381    52098      0  110320  120074       310431  192261     38120  142327       189762  136224        167091  155882   245316  184754
2014    127205  124692  133961       194272  125443     93160      0  46205  263437       50171    58849   176191   89590   88136    49431      0  109521  116771       190265  189742     27886  130076       171783  129210        157584  170011   245896  182508
2015    124796  122271  139661       158853  128962     78060      0  46258  275793       35453    31426    96131   94283   72631    56902  31118  113177  115161       107962  192946     28707  109438        84635  132800        138590  173267    95895  184260
2016    111868  117519  147590       151286  127651     55952  33239  44969  279489       32775    32311    96402   96785   77294    58963  31037  115005  113429       114603  195643     29349  111281        87483  138865        133486  169251    97421  183738
2017    113257  100090  186452       126226  123887     58283  34996  44749  284150       35493    32631    94139   38917   94736    66425  31098  111513  123310       132461  200733     31402  111059       105286  152450         72186  172040   111828  186900
2018    116121   98830  190635       140205  110637     61524  40843  45616  298218       55671    37052    93968   38901  113017    71494  31871  116348  123213       163138  205208     31323  114075       114283  170897         86237  179906   106528  194889
2019    120998  100411  191456       151721  112322     67257  46341  46525  345841       41608    41006    93561   64933  117323    77136  33003  122342  129431       180801  205591     32144  116644       123448  174098         95328  182764   109034  200124
2020     35701   81404  123197        94895  262620     19116  93342   6816  252332      126775    87370    79233   68230  102778    68737  37025   95015   85176        34811   83341     19034   64718        64949   51711         92211   17319    95420   49114
2021     37779   82286  126625        96923  270346     19545  94356   6922  255690      129039    88649    80136   70678  102800    69431  37787   95615   85263        35589   84241     19377   64770        63294   51875         92295   17326    94960   49340

In [58]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Gujarat"
    
}
Gujarat_meta = transform_data(Gujarat,doc_source)
Gujarat_meta

Year,Ahmadabad,Amreli,Anand,Banas Kantha,Bharuch,Bhavnagar,Botad,Dang,Dohad,Gandhinagar,Jamnagar,Junagadh,Kachchh,Kheda,Mahesana,Morbi,Narmada,Navsari,Panch Mahals,Patan,Porbandar,Rajkot,Sabar Kantha,Surat,Surendranagar,Tapi,Vadodara,Valsad
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat,Gujarat

In [59]:
uuid = load_data(Gujarat,Gujarat_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5241
uuid is 5242
uuid is 5243
uuid is 5244
uuid is 5245
uuid is 5246
uuid is 5247
uuid is 5248
uuid is 5249
uuid is 5250
uuid is 5251
uuid is 5252
uuid is 5253
uuid is 5254
uuid is 5255
uuid is 5256
uuid is 5257
uuid is 5258
uuid is 5259
uuid is 5260
uuid is 5261
uuid is 5262
uuid is 5263
uuid is 5264
uuid is 5265
uuid is 5266
uuid is 5267
uuid is 5268

## Haryana

In [60]:
Haryana = statedic[states_list[12]]
Haryana

Year  Ambala Bhiwani Faridabad Fatehabad Gurugram  Hisar Jhajjar    Jind Kaithal  Karnal Kurukshetra Mahendragarh   Mewat  Palwal Panchkula Panipat  Rewari  Rohtak   Sirsa Sonipat Yamunanagar

2012   39714   57426      4144     36993     4845  60336   26857   31956   24198   33174       24409        65562   35023   17395     10083   16009   29716   13992   86846   31416       27760
2013   40573   61440      5364     44233     5572  82258   29950   34168   25684   39128       27106        66778   37244   20850     12578   17171   30645   14964   92483   32227       29817
2014   23607   69728      8223     48555     7754  88618   41678   35364   28009   44008       34801        54572   43796   25153     12133   18981   31133   15690   93151   26976       27925
2015   22810   68743      7784     44817     8360  84383   44055   37631   30009   47989       36215        46874   43937   23167     13452   19541   31135   16523   89887   27921       27642
2016   24047   71103      4216     44831     8805  79114   42942   40705   29952   48216       37178        36701   44502   17028     13480   20201   31699   16121   91480   28793       29024
2017   25573   85607      3309     48365     9652  92184   47131   45975   34605   57048       40237        43100   44815   19165     11934   23095   32865   22040  101680   26605       32692
2018   27015   68147      3428     51100     9644  89897   48070   50271   38539   63849       42525        45014   50523   20416     12241   24959   33284   23568  104766   23377       33782
2019   28393   68897      3644     54778    10136  93341   48810   53581   40921   67680       44895        46890   59470   21502     12454   26344   33502   24105  108298   25222       34914
2020  119266   51266     65190     25293    31304   6891   66672  235096  220378  244018      216263       248750  232791  257695    334546  236163  206244  232410  148818  109955       89753
2021  118741   52609     65384     26226    31351   6940   65265  250154  226894  253240      230537       261707  242850  272521    360040  255115  212687  254740  160545  115602      106562

In [61]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Haryana"
    
}
Haryana_meta = transform_data(Haryana,doc_source)
Haryana_meta

Year,Ambala,Bhiwani,Faridabad,Fatehabad,Gurugram,Hisar,Jhajjar,Jind,Kaithal,Karnal,Kurukshetra,Mahendragarh,Mewat,Palwal,Panchkula,Panipat,Rewari,Rohtak,Sirsa,Sonipat,Yamunanagar
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana,Haryana

In [62]:
uuid = load_data(Haryana,Haryana_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5269
uuid is 5270
uuid is 5271
uuid is 5272
uuid is 5273
uuid is 5274
uuid is 5275
uuid is 5276
uuid is 5277
uuid is 5278
uuid is 5279
uuid is 5280
uuid is 5281
uuid is 5282
uuid is 5283
uuid is 5284
uuid is 5285
uuid is 5286
uuid is 5287
uuid is 5288
uuid is 5289

## Himachal Pradesh

In [63]:
Himachal_Pradesh = statedic[states_list[13]]
Himachal_Pradesh

Year Bilaspur  Chamba Hamirpur  Kangra Kinnaur   Kullu Lahul And Spiti   Mandi  Shimla Sirmaur   Solan     Una

2012    55011   99777    80800  223249   13294   86699            5774  208298  112021   74536   77454   69749
2013    62127  103864    82894  231933   13784   88785            5978  217231  117724   76925   79832   70975
2014    66977  105976    82895  236960   15123   89073            6198  220651  119109   79009   80144   67127
2015    69873  107259    84101  241115   15773   90119            6297  224653  118933   79221   77581   63203
2016    71348  108708    84802  243770   16590   90688            6424  229667  118858   78613   74930   62424
2017    73991  110385    85138  247836   17381   90807            6560  236999  117706   80847   74514   60611
2018    76601  112409    88025  252942   17797   90078            6617  241854  120943   82433   74939   62398
2019    79237  117208    91468  257578   18452   91548            6712  246673  123884   85546   77324   65448
2020   163696   75998   184641  321335   81548  348941          193316  166626  131820  312727  195784  329529
2021   174005   80363   197759  330417   86139  358225          218442  175338  143568  323419  204954  344967

In [64]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Himachal Pradesh"
    
}
Himachal_Pradesh_meta = transform_data(Himachal_Pradesh,doc_source)
Himachal_Pradesh_meta

Year                                                 Bilaspur                                             Chamba                                           Hamirpur                                             Kangra                                            Kinnaur                                              Kullu                                    Lahul And Spiti                                              Mandi                                             Shimla                                            Sirmaur                                              Solan                                                Una
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                        Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh                                   Himachal Pradesh

In [65]:
uuid = load_data(Himachal_Pradesh,Himachal_Pradesh_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5290
uuid is 5291
uuid is 5292
uuid is 5293
uuid is 5294
uuid is 5295
uuid is 5296
uuid is 5297
uuid is 5298
uuid is 5299
uuid is 5300
uuid is 5301

## Jammu and Kashmir

In [66]:
Jammu_and_Kashmir = statedic[states_list[14]]
Jammu_and_Kashmir

Year Anantnag Badgam Bandipora Baramulla    Doda Ganderbal   Jammu  Kargil  Kathua Kishtwar  Kulgam Kupwara Leh (Ladakh)  Poonch Pulwama Rajauri  Ramban   Reasi   Samba Shopian Srinagar Udhampur

2012    54411  45204     22224     74828   92188     28126   56790   15376   48295    64003   30895   52955        15428   75345   30029   83703   46402   45497   25155   17735     2458    55708
2013    67486  56341     30653     89077   90842     33114   77807   16977   56751    74289   50056   76887        16205   86230   33682  104220   50409   49662   29293   25114     2460    60986
2014    72022  60526     32470     92539   85792     35560   97043   16776   59549    75056   53717   88070        16356   90031   39299  103429   51491   62432   31325   30172     2566    62437
2015    79197  61066     34833     96538   82262     35839   94223   17366   60657    74630   55802   86732        16783   87367   42734  114374   49977   63485   31169   31610     3649    63600
2016    91509  64350     36152     99392   82703     36690   97469   17992   64134    75166   59248   92968        16961   92447   45721  119240   50204   63081   32216   33274     6540    65396
2017    91631  60890     33909     93667   79789     34528   83803   18169   59692    65702   58996   86228        17160   94774   45942  114736   43822   58437   28619   27925     6930    64127
2018    95866  64771     35162     93235   78724     34958   82941   18180   58284    60398   50938   88895        16927   84404   47096  115167   43148   58994   24788   29282     6916    63292
2019   102984  67250     36763     94112   81072     35063   79264   18665   59824    64028   51177   91695        17106   92914   48689  114964   47199   62161   24454   30601     6799    63786
2020   612834  44288     83087    166728  171055    185917  146271  284371  128892   193889  138483  144344       249008  213492  284681   66695  211180  241750  280692  266264   273703   169109
2021   641200  44956     88636    194554  198012    194847  148620  293955  132296   199272  140461  149327       252024  222737  326408   68020  216306  252927  286781  278478   289751   179270

In [67]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Jammu and Kashmir"
    
}
Jammu_and_Kashmir_meta = transform_data(Jammu_and_Kashmir,doc_source)
Jammu_and_Kashmir_meta

Year,Anantnag,Badgam,Bandipora,Baramulla,Doda,Ganderbal,Jammu,Kargil,Kathua,Kishtwar,Kulgam,Kupwara,Leh (Ladakh),Poonch,Pulwama,Rajauri,Ramban,Reasi,Samba,Shopian,Srinagar,Udhampur
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir,Jammu and Kashmir

In [68]:
uuid = load_data(Jammu_and_Kashmir,Jammu_and_Kashmir_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5302
uuid is 5303
uuid is 5304
uuid is 5305
uuid is 5306
uuid is 5307
uuid is 5308
uuid is 5309
uuid is 5310
uuid is 5311
uuid is 5312
uuid is 5313
uuid is 5314
uuid is 5315
uuid is 5316
uuid is 5317
uuid is 5318
uuid is 5319
uuid is 5320
uuid is 5321
uuid is 5322
uuid is 5323

## Jharkhand

In [69]:
Jharkhand = statedic[states_list[15]]
Jharkhand

Year  Bokaro  Chatra Deoghar Dhanbad   Dumka East Singhbum  Garhwa Giridih   Godda   Gumla Hazaribagh Jamtara  Khunti Koderma Latehar Lohardaga   Pakur  Palamu Ramgarh  Ranchi Sahebganj Saraikela Kharsawan Simdega West Singhbhum

2012  175935  164676  189025  169689  210366        217304  195087  219713  195722  184770     183316  111302  107969   64119  141800     70439  166434  226587   91917  299576    144962              144501  112310         253478
2013  175315  165389  185295  171901  213048        218408  196340  221438  185939  184163     171191  114334  108960   66099  146260     70597  166563  226182   86760  303713    144769              145841  112848         252975
2014  165310  154434  181821  166613  206733        203925  154922  187642  183311  182434     160883  114393  100047   52223  127624     68266  158079  198041   71582  304068    132634              142816  100874         252404
2015  164871  153127  178641  146613  189607        195267  158205  182010  177247  181419     164362  113444  100257   51654  110197     68723  146289  193042   73709  305931    118468              144160  100267         250491
2016  168144  156451  188802  148990  201282        198685  162703  189431  185022  181672     170793  114169  104059   53107  117582     69224  146032  204595   70380  309280    124284              146523  105548         257932
2017  196772  192937  209966  174536  211842        207214  218310  249882  200098  190481     212734  122588  111102   66347  138164     72580  159954  260593   77068  332387    146967              155335  112966         283227
2018  209203  197500  210899  188522  200646        215306  224455  267973  211808  194571     204959  126965   99479   71299  134852     72845  163470  277026   70230  326317    162648              152960  120617         292144
2019  221099  214492  229277  203032  228903        224197  248450  307236  222892  200356     219492  136259  103131   82058  152038     74411  175447  300972   77016  336910    176418              158947  125264         301811
2020  215211  388181   70079  162887  244901        179664  277501  239581  198256  223175     158516  365795  195821  309059  331342    359087  145025  402491  287080  146611      8212               83723  123141         135504
2021  221926  399132   72359  165407  260783        198469  280895  243094  201706  226401     160194  370702  199817  313783  335766    362213  147471  408163  292341  147853      8217               81786  125874         138037

In [70]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Jharkhand"
    
}
Jharkhand_meta = transform_data(Jharkhand,doc_source)
Jharkhand_meta

Year,Bokaro,Chatra,Deoghar,Dhanbad,Dumka,East Singhbum,Garhwa,Giridih,Godda,Gumla,Hazaribagh,Jamtara,Khunti,Koderma,Latehar,Lohardaga,Pakur,Palamu,Ramgarh,Ranchi,Sahebganj,Saraikela Kharsawan,Simdega,West Singhbhum
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand,Jharkhand

In [71]:
uuid = load_data(Jharkhand,Jharkhand_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5324
uuid is 5325
uuid is 5326
uuid is 5327
uuid is 5328
uuid is 5329
uuid is 5330
uuid is 5331
uuid is 5332
uuid is 5333
uuid is 5334
uuid is 5335
uuid is 5336
uuid is 5337
uuid is 5338
uuid is 5339
uuid is 5340
uuid is 5341
uuid is 5342
uuid is 5343
uuid is 5344
uuid is 5345
uuid is 5346
uuid is 5347

## Karnataka

In [72]:
Karnataka = statedic[states_list[16]]
Karnataka

Year Bagalkote Ballari Belagavi Bengaluru Bengaluru Rural   Bidar Chamaraja Nagara Chikkaballapura Chikkamagaluru Chitradurga Dakshina Kannada Davanagere Dharwar   Gadag  Hassan  Haveri Kalaburagi Kodagu   Kolar  Koppal  Mandya  Mysuru Raichur Ramanagara Shivamogga Tumakuru   Udupi Uttara Kannada Vijaypura  Yadgir

2012    200218  234294   541233     60995           77394  206324           103548          136856         131608      239867            93972     239988  119120  125759  218744  175010     237005  60601  197415  234163  204341  166307  234654     134087     183475   268194   35148         142841    352082  236283
2013    202567  234200   541100     51383           76537  211305           114417          138559         129897      247851            77502     248345  124890  120360  220596  173173     264434  65015  197252  203492  173559  177586  245480     136843     180950   283677   35793         142402    260081  196923
2014    208158  207401   499636     49802           80078  188989           129339          151482         128335      255846            72211     246966  126726  113242  220526  177733     307799  64429  195807  221033  188105  196150  258092     162617     177537   312869   40628         144072    248028  212927
2015    199560  215978   493664     49213           75516  170572           131404          158980         130591      248406            73042     234775  125525  116244  226123  178631     280240  64089  194681  217141  230540  196352  256790     167383     183772   311804   45899         149461    216344  200614
2016    169570  224860   523530     48684           70200  168983           140424          166580         133274      249656            82749     235817  126151  122269  228604  184123     202751  64413  198673  218468  241905  212621  291757     170594     194372   318446   51381         154381    218323  199671
2017    159106  236392   495785     41936           67322  135939           142747          166299         133718      236255            95290     218498  129977  128834  234385  183330     191361  63917  196512  203568  252793  214083  170514     154487     197919   326822   54352         154066    196907  123052
2018    159745  245560   540469     42700           68107  124522           150290          173259         136650      256218           113604     227833  132796  131539  237996  194702     205105  63680  193362  212770  262089  233318  195448     161754     203572   342635   60984         154941    200074  136241
2019    179777  312564   586674     43594           80055  145586           160449          179644         141226      274450           123021     190189  135849  137673  244176  207204     251560  65305  204457  226921  272585  253901  245917     163577     210326   355738   66807         160780    219316  164748
2020     82413  302431   150005    202153          114952   34738            76624          173498         231829      169134            41951     135178  322706  182694  149006   70933      40026  63455   56907  128412  205168  149786  176840     217356     215798   135259  140402         107492     67033  126310
2021     89808  304383   157280    205773          127041   25337            79026          182373         241364      175280            47897     140322  334870  184655  144814   68876      37794  56249   53043  135294  212229  151962  179276     225388     219474   108339  144818         114814     68644  125011

In [73]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Karnataka"
    
}
Karnataka_meta = transform_data(Karnataka,doc_source)
Karnataka_meta

Year,Bagalkote,Ballari,Belagavi,Bengaluru,Bengaluru Rural,Bidar,Chamaraja Nagara,Chikkaballapura,Chikkamagaluru,Chitradurga,Dakshina Kannada,Davanagere,Dharwar,Gadag,Hassan,Haveri,Kalaburagi,Kodagu,Kolar,Koppal,Mandya,Mysuru,Raichur,Ramanagara,Shivamogga,Tumakuru,Udupi,Uttara Kannada,Vijaypura,Yadgir
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka,Karnataka

In [74]:
uuid = load_data(Karnataka,Karnataka_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5348
uuid is 5349
uuid is 5350
uuid is 5351
uuid is 5352
uuid is 5353
uuid is 5354
uuid is 5355
uuid is 5356
uuid is 5357
uuid is 5358
uuid is 5359
uuid is 5360
uuid is 5361
uuid is 5362
uuid is 5363
uuid is 5364
uuid is 5365
uuid is 5366
uuid is 5367
uuid is 5368
uuid is 5369
uuid is 5370
uuid is 5371
uuid is 5372
uuid is 5373
uuid is 5374
uuid is 5375
uuid is 5376
uuid is 5377

## Kerala

In [75]:
Kerala = statedic[states_list[17]]
Kerala

Year Alappuzha Ernakulam  Idukki  Kannur Kasargod  Kollam Kottayam Kozhikode Malappuram Palakkad Pathanamthitta Thiruvananthapuram Thrissur Wayanad

2012    174564    134969  126286  104670    71251  152583   122188    168978     165342   164459          77745             208040   123216   92483
2013    214764    168291  155486  161235    98141  233141   148297    214507     219490   225193         112535             277997   212210  112903
2014    229834    183182  165737  180430   112187  264276   160702    242020     248929   255549         120783             313027   236703  121697
2015    239323    198850  170868  190925   122132  283957   167148    259180     273046   280716         127580             331932   247998  134486
2016    248534    206937  177993  203880   130704  307515   172606    278709     294569   305806         132377             349506   259290  139604
2017    251982    208764  177588  195305   139313  311938   172739    274183     291748   316238         129684             364738   259312  130870
2018    259525    216645  184015  204154   145792  328969   179252    284268     304121   328549         134181             375247   267326  136186
2019    269131    229840  192489  213726   153047  349708   188491    297864     318479   347552         139355             390681   278595  143776
2020     99303    229881  144805  187328   253719  163818    95626    200612     162771    69435          85605             157172   117055  175713
2021    108109    234841  150960  200762   269028  175329    73394    209678     163748    72287          88018             168954   128718  174773

In [76]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Kerala"
    
}
Kerala_meta = transform_data(Kerala,doc_source)
Kerala_meta

Year                                                Alappuzha                                          Ernakulam                                             Idukki                                             Kannur                                           Kasargod                                             Kollam                                           Kottayam                                          Kozhikode                                         Malappuram                                           Palakkad                                     Pathanamthitta                                 Thiruvananthapuram                                           Thrissur                                            Wayanad
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                                  Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala                                             Kerala

In [77]:
uuid = load_data(Kerala,Kerala_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5378
uuid is 5379
uuid is 5380
uuid is 5381
uuid is 5382
uuid is 5383
uuid is 5384
uuid is 5385
uuid is 5386
uuid is 5387
uuid is 5388
uuid is 5389
uuid is 5390
uuid is 5391

## Madhya Pradesh

In [78]:
Madhya_Pradesh = statedic[states_list[18]]
Madhya_Pradesh

Year Agar-Malwa Alirajpur Anuppur Ashok Nagar Balaghat Barwani   Betul   Bhind  Bhopal Burhanpur Chhatarpur Chhindwara   Damoh  Datia   Dewas    Dhar Dindori    Guna Gwalior  Harda Hoshangabad  Indore Jabalpur  Jhabua   Katni Khandwa Khargone  Mandla Mandsaur  Morena Narsinghpur Neemuch   Panna  Raisen Rajgarh  Ratlam    Rewa   Sagar   Satna  Sehore   Seoni Shahdol Shajapur Sheopur Shivpuri   Sidhi Singrauli Tikamgarh  Ujjain  Umaria Vidisha

2012          0    130947  145761      235126   399234  247515  275589  193569   87360     91617     283866     357586  259152  91532  207854  357330  226326  228028  161708  85542      208479  179387   298016  219958  268100  330528   307247  279639   242887  269520      234055  134555  223121  194223  284824  232643  397388  448837  381294  214177  296843  212333   305176  123184   323667  230407    211455    246566  244193  177133  192363
2013          0    132170  158256      238302   414608  248173  284136  194045   86781     94493     289228     372269  264751  94430  208728  369477  231841  229867  162282  86729      207887  180254   294881  213287  275650  329468   339063  284401   242770  266942      234137  134767  225324  195383  321168  233211  408896  453304  382673  216622  310740  209741   305924  125474   296902  231315    215374    247675  248560  173140  196431
2014          0    129481  156666      216310   392115  239973  216139  193124   54776     89011     236032     275894  235819  76262  179999  358267  208416  222581   99378  61923      125576   87839   236912  209348  191862  223980   310788  263907   220311  179431      146636  107109  204911  124274  280620  171381  328169  367720  306137  158873  279533  184818   285582  117753   226368  210627    205315    194086  197529  158528  142782
2015          0    114765  150111       82746   371432  238814  214776  188496   55939     87669     182104     272738  190884  57177  155652  355164  197976  192495  105021  53346      120164   67469   185902  207064  166318  210791   214749  253452   195101  197400      115150   86913  171270   85074  279437  172187  229357  361493  185563  140469  238912  179045   282406  102397   196643  159289    198462    158206  175552  149474  110722
2016     106152    116014  144796       81040   365978  237515  213148  194144   51976     85372     162658     265436  184125  56910  152227  342072  184181  188929   88087  49719      108854   68754   145558  206131  165548  208695   210386  234380   188644  193107      113761   81368  165618   90776  257347  163554  229876  334120  178970  134819  229302  176538    95497  102267   192344  142229    197169    139280  129203  144257  107961
2017      84500    114989  130029       65347   305207  189689  206595   99685   36039     74426     134024     230655  151332  37619  117012  313344  170423  132519   58851  40936       75293   51090   123321  193785  139696  175268   197570  208908   128080  100374      107557   62617  132480   90420  226905  138061  179392  223696  140977  111039  202710  164834    59297   79243   119338  113731    161557    120188  103003  116112   85468
2018      83506    112972  127764       66328   293474  182839  209051  103398   38224     74250     143502     223882  152873  37823  121282  303758  169207  135764   58677  39246       73955   51768   125449  190170  142060  175656   201694  204755   132006   95517      110154   60968  130448  103983  220092  141047  177971  227083  153881  103173  199867  157077    60248   83512   122254  112205    158300    114082   93537  117186  101338
2019      84042    118176  131756       77075   302091  140646  212438  112735   41928     75368     160650     225022  161583  41775  130370  317753  176207  143720   66069  40072       75680   55003   130293  197767  146231  171694   213793  215366   141230  121135      108291   63827  131297  107891  229477  148354  191339  244327  167249  102732  200172  162377    65949   91336   142274  113767    167269    122752   88621  123100  113914
2020     234934    238192  185058      407834   346095  426632  238108  228715  232956    113346     173324     212970  286611  90648  359091  103381  157390  196259  438373  50708       35786   62632   117445   61531   79376   32200    84158   48669    30836  100302       58543   39603  106167   53825   65885   27321   29647   19396   33035   38794   21062   16135    14769   74746    23827   53981     21738     35754   43915   27969   34454
2021     235592    239124  186790      409369   352554  431310  238474  230017  238402    114845     174691     214537  289746  91858  356631  103632  158641  195058  440204  52595       35783   62736   118027   61712   79380   32308    84143   48775    32311  103256       58964   41366  107685   54807   67122   27559   29610   19549   33787   38629   21247   16352    14972   74746    23848   53845     21738     35744   45616   27969   35047

In [79]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Madhya Pradesh"
    
}
Madhya_Pradesh_meta = transform_data(Madhya_Pradesh,doc_source)
Madhya_Pradesh_meta

Year,Agar-Malwa,Alirajpur,Anuppur,Ashok Nagar,Balaghat,Barwani,Betul,Bhind,Bhopal,Burhanpur,Chhatarpur,Chhindwara,Damoh,Datia,Dewas,Dhar,Dindori,Guna,Gwalior,Harda,Hoshangabad,Indore,Jabalpur,Jhabua,Katni,Khandwa,Khargone,Mandla,Mandsaur,Morena,Narsinghpur,Neemuch,Panna,Raisen,Rajgarh,Ratlam,Rewa,Sagar,Satna,Sehore,Seoni,Shahdol,Shajapur,Sheopur,Shivpuri,Sidhi,Singrauli,Tikamgarh,Ujjain,Umaria,Vidisha
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh,Madhya Pradesh

In [80]:
uuid = load_data(Madhya_Pradesh,Madhya_Pradesh_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5392
uuid is 5393
uuid is 5394
uuid is 5395
uuid is 5396
uuid is 5397
uuid is 5398
uuid is 5399
uuid is 5400
uuid is 5401
uuid is 5402
uuid is 5403
uuid is 5404
uuid is 5405
uuid is 5406
uuid is 5407
uuid is 5408
uuid is 5409
uuid is 5410
uuid is 5411
uuid is 5412
uuid is 5413
uuid is 5414
uuid is 5415
uuid is 5416
uuid is 5417
uuid is 5418
uuid is 5419
uuid is 5420
uuid is 5421
uuid is 5422
uuid is 5423
uuid is 5424
uuid is 5425
uuid is 5426
uuid is 5427
uuid is 5428
uuid is 5429
uuid is 5430
uuid is 5431
uuid is 5432
uuid is 5433
uuid is 5434
uuid is 5435
uuid is 5436
uuid is 5437
uuid is 5438
uuid is 5439
uuid is 5440
uuid is 5441
uuid is 5442

## Maharashtra

In [81]:
Maharashtra = statedic[states_list[19]]
Maharashtra

Year Ahmednagar   Akola Amravati Aurangabad    Beed Bhandara Buldhana Chandrapur   Dhule Gadchiroli  Gondia Hingoli Jalgaon   Jalna Kolhapur   Latur  Nagpur  Nanded Nandurbar  Nashik Osmanabad Parbhani    Pune  Raigad Ratnagiri  Sangli  Satara Sindhudurg Solapur   Thane  Wardha  Washim Yavatmal

2012     534767  134327   277712     381301  228161   202781   235824     244767  179662     166994  212856  126671  230028  182964   171646  176590  130808  359150    231995  265796    208755   132131  183999  129833    115811  148095  194234      64430  263125  254261   90425  110345   335642
2013     599852  170913   285153     441472  267577   204960   243493     251664  186089     178067  216392  127798  241716  222319   177349  182186  130872  360740    232411  294474    215002   143458  194895  134293    127375  164098  204395      63445  282453  262143  108965  128088   344472
2014     605573  174880   293430     438068  277746   206906   249090     256159  191838     177764  218389  129875  253398  231282   176743  185938  135445  362019    228514  303154    214563   157048  199783  135746    130768  178058  231339      61660  292556  265158  111861  143537   348125
2015     609752  178186   293616     441479  289647   202744   248460     260792  197258     178168  220157  129007  261797  242402   177225  190841  137114  367752    231790  308892    216963   171156  205945  137931    137572  188037  238379      66526  295629  268212  129037  155940   356838
2016     617057  181851   299438     446199  314150   199955   269612     264218  205637     180611  225796  133954  281563  253045   180764  198914  147194  373445    242857  321725    219176   199351  215279  142445    142738  190995  242803      69942  294915   94292  125071  167459   374386
2017     629726  191560   309574     455432  324739   202112   287851     268684  226510     173679  238344  142961  325444  260770   200899  209886  160642  385727    264457  357447    223687   201557  235059  149259    152127  203748  266416      76558  315731  102012  129403  179306   391223
2018     623197  203595   332534     466355  342578   211912   316611     280986  258283     175706  262848  152359  382223  278661   218821  223347  174280  407297    306354  405183    221474   216094  237330  113519    157538  210395  272296      82930  346992  100841  146133  191076   417245
2019     630159  210687   341524     479365  357302   220135   324793     282860  266545     179075  272936  158363  397341  292082   230608  231745  177793  404920    332613  417446    233033   224047  225027  108882    166904  208905  278762      87196  351784  102372  150729  196573   430710
2020      48703   34448    37807     189800  362446   254611   275144     319343  100743     288225   69820  195561  126414  534318   141808  298593   72337  310830    153051  233109    334146   145420  295558  111477    486471  266178  170208     134255  249527  205622  127419  124245   313186
2021      48605   34739    37807     197876  373899   271375   291438     342383  104006     293330   71910  207901  116026  544232   148746  307312   74018  331079    160721  244560    346767   151723  303127  116727    506233  275789  173608     141538  256785  209301  132643  129937   322920

In [82]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Maharashtra"
    
}
Maharashtra_meta = transform_data(Maharashtra,doc_source)
Maharashtra_meta

Year,Ahmednagar,Akola,Amravati,Aurangabad,Beed,Bhandara,Buldhana,Chandrapur,Dhule,Gadchiroli,Gondia,Hingoli,Jalgaon,Jalna,Kolhapur,Latur,Nagpur,Nanded,Nandurbar,Nashik,Osmanabad,Parbhani,Pune,Raigad,Ratnagiri,Sangli,Satara,Sindhudurg,Solapur,Thane,Wardha,Washim,Yavatmal
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra

In [83]:
uuid = load_data(Maharashtra,Maharashtra_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5443
uuid is 5444
uuid is 5445
uuid is 5446
uuid is 5447
uuid is 5448
uuid is 5449
uuid is 5450
uuid is 5451
uuid is 5452
uuid is 5453
uuid is 5454
uuid is 5455
uuid is 5456
uuid is 5457
uuid is 5458
uuid is 5459
uuid is 5460
uuid is 5461
uuid is 5462
uuid is 5463
uuid is 5464
uuid is 5465
uuid is 5466
uuid is 5467
uuid is 5468
uuid is 5469
uuid is 5470
uuid is 5471
uuid is 5472
uuid is 5473
uuid is 5474
uuid is 5475

## Manipur

In [84]:
Manipur = statedic[states_list[20]]
Manipur

Year Bishnupur Chandel Churachandpur Imphal East Imphal West Senapati Tamenglong Thoubal  Ukhrul

2012     36299   34466         58078       78848       53069    77842      26691   57800   49111
2013     36277   34660         58495       82542       53215    77946      27182   62253   52456
2014     45430   34599         56730       90871       52933    78154      28016   75451   52061
2015     45462   35408         58283       93890       54725    81265      29487   80207   53375
2016     47729   35389         60532       95046       61560    80632      30190   80454   53390
2017     47957   34477         62180       97585       61617    80750      30566   80757   52618
2018     47255   35349         61959      100711       61567    80909      31365   80691   50247
2019     50445   35478         62191      114456       61523    80695      31719   83211   48271
2020     15813   54290        126886       34069       96311    49904      50195  123464  115227
2021     16567   56321        130549       34743       96715    50818      51255  125234  117508

In [85]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Manipur"
    
}
Manipur_meta = transform_data(Manipur,doc_source)
Manipur_meta

Year                                                Bishnupur                                            Chandel                                      Churachandpur                                        Imphal East                                        Imphal West                                           Senapati                                         Tamenglong                                            Thoubal                                             Ukhrul
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                                 Manipur                                            Manipur                                            Manipur                                            Manipur                                            Manipur                                            Manipur                                            Manipur                                            Manipur                                            Manipur

In [86]:
uuid = load_data(Manipur,Manipur_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5476
uuid is 5477
uuid is 5478
uuid is 5479
uuid is 5480
uuid is 5481
uuid is 5482
uuid is 5483
uuid is 5484

## Meghalaya

In [87]:
Meghalaya = statedic[states_list[21]]
Meghalaya

Year East Garo Hills East Khasi Hills Ri Bhoi South Garo Hills West Garo Hills West Jaintia Hills West Khasi Hills

2012           52729            80652   48257            25480          128461              59215            62746
2013           55395            82136   49012            28054          127334              60474            65030
2014           29606            80721   49453            27722           94705              41762            52018
2015           29784            82054   51967            30192           87197              45206            54078
2016           28560            82345   53188            31281           87415              46966            55069
2017           29081            85788   54594            35910           90127              48368            57273
2018           30346            88751   55767            37294           96077              48210            59541
2019           29804            94842   56629            37395          102363              51097            63914
2020          103719           110303   66023            41766          136491              74305            84776
2021          109541           114641   68756            42984          140108              75494            83435

In [88]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Meghalaya"
    
}
Meghalaya_meta = transform_data(Meghalaya,doc_source)
Meghalaya_meta

Year                                          East Garo Hills                                   East Khasi Hills                                            Ri Bhoi                                   South Garo Hills                                    West Garo Hills                                 West Jaintia Hills                                   West Khasi Hills
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District
State                                               Meghalaya                                          Meghalaya                                          Meghalaya                                          Meghalaya                                          Meghalaya                                          Meghalaya                                          Meghalaya

In [89]:
uuid = load_data(Meghalaya,Meghalaya_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5485
uuid is 5486
uuid is 5487
uuid is 5488
uuid is 5489
uuid is 5490
uuid is 5491

## Mizoram

In [90]:
Mizoram = statedic[states_list[22]]
Mizoram

Year Aizawl Champhai Kolasib Lawngtlai Lunglei   Mamit  Saiha Serchhip

2012  39408    29556    3200     29212   37313   25585  11588    14237
2013  38767    32022   18442     30521   42975   25697  14283    14680
2014  26911    28915   20406     31119   38537   20447  15315    14929
2015  24614    28816   18485     27640   32892   20275  14334    14474
2016  27158    28539   17791     29306   34351   20694  14457    14222
2017  27808    29558   18190     29710   35409   20761  14638    14401
2018  28637    29031   18444     29655   36198   20490  14645    14226
2019  27197    29313   18808     31373   36917   20536  15175    14626
2020  95043    42056   39079    120080   44057   99719  33245   119359
2021  96388    44332   40156    121890   46557  101440  34394   122287

In [91]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Mizoram"
    
}
Mizoram_meta = transform_data(Mizoram,doc_source)
Mizoram_meta

Year                                                   Aizawl                                           Champhai                                            Kolasib                                          Lawngtlai                                            Lunglei                                              Mamit                                              Saiha                                           Serchhip
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                                 Mizoram                                            Mizoram                                            Mizoram                                            Mizoram                                            Mizoram                                            Mizoram                                            Mizoram                                            Mizoram

In [92]:
uuid = load_data(Mizoram,Mizoram_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5492
uuid is 5493
uuid is 5494
uuid is 5495
uuid is 5496
uuid is 5497
uuid is 5498
uuid is 5499

## Odisha

In [93]:
Odisha = statedic[states_list[23]]
Odisha

Year   Angul Baleshwar Bargarh Bhadrak Bolangir   Boudh Cuttack Deogarh Dhenkanal Gajapati  Ganjam Jagatsinghapur  Jajpur Jharsuguda Kalahandi Kandhamal Kendrapara Kendujhar Khordha Koraput Malkangiri Mayurbhanj Nabarangapur Nayagarh Nuapada    Puri Rayagada Sambalpur Sonepur Sundargarh

2012  178121    310389  253838  207726   262139   83451  221123   59389    174689   125134  448618         131960  269311      73423    288539    157090     187291    310638  104532  281605     127340     433310       220667   152377  115609  217518   187308    157183  105550     318068
2013  181492    322541  254813  231812   269234   85686  231043   61734    176100   127153  456088         140278  269980      72809    292995    161013     194179    318660  108888  284183     128841     435454       222376   156906  118010  219751   191466    157210  106825     341007
2014  185044    327853  254420  240553   276717   88509  238617   63482    174999   128972  467886         149029  272902      73003    297199    153662     201034    326199  118488  287954     129511     382434       224388   158632  119454  223103   194606    152688  109674     351159
2015  188500    335920  258010  250551   285692   90505  249841   65852    178672   130344  479560         153887  276575      74244    302392    156888     205847    333278  122840  296027     133363     394489       227927   162937  120463  226968   199296    153446  110400     359040
2016  192822    347976  261546  256163   294458   92403  256216   69311    180467   132704  494598         157909  279078      74382    310890    158031     214236    343536  127750  299597     134033     414436       231834   165368  124484  232732   204619    154397  112390     364286
2017  189794    336490  251474  227339   296886   90916  266078   67558    171087   130952  492638         140332  278276      68872    302195    147839     220371    307848  133230  294560     101542     419315       236126   162435  124026  226091   202290    136159  113001     297710
2018  179029    354780  243439  238294   288154   87954  276814   65683    182222   121343  492366         131500  280466      64820    288700    141904     213154    304962  137700  280600      99676     426350       240052   164594  124315  233689   197317    122120  112225     284143
2019  182863    357137  249287  248102   296628   93052  280996   67319    186023   122158  503697         134512  286930      67154    292704    145742     219500    314420  141171  284596     102952     441508       244101   168225  126854  238843   199378    121999  116039     291421
2020  331486    180189  505492  253995   169646  533145  360344  205067    225527   242470  283625         171726  330785     278924    540970     22716       7960     24944   28166  176837     169136     455078       239594   332605  208101  342809   114004    148012  278535     297152
2021  346285    194145  522169  263782   176534  562833  386092  213895    246887   251937  299632         189191  336535     288306    567958     22928       8001     25127   28451  178015     167662     453356       248846   337408  210629  342811   114317    150698  282533     297724

In [94]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Odisha"
    
}
Odisha_meta = transform_data(Odisha,doc_source)
Odisha_meta

Year,Angul,Baleshwar,Bargarh,Bhadrak,Bolangir,Boudh,Cuttack,Deogarh,Dhenkanal,Gajapati,Ganjam,Jagatsinghapur,Jajpur,Jharsuguda,Kalahandi,Kandhamal,Kendrapara,Kendujhar,Khordha,Koraput,Malkangiri,Mayurbhanj,Nabarangapur,Nayagarh,Nuapada,Puri,Rayagada,Sambalpur,Sonepur,Sundargarh
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha,Odisha

In [95]:
uuid = load_data(Odisha,Odisha_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5500
uuid is 5501
uuid is 5502
uuid is 5503
uuid is 5504
uuid is 5505
uuid is 5506
uuid is 5507
uuid is 5508
uuid is 5509
uuid is 5510
uuid is 5511
uuid is 5512
uuid is 5513
uuid is 5514
uuid is 5515
uuid is 5516
uuid is 5517
uuid is 5518
uuid is 5519
uuid is 5520
uuid is 5521
uuid is 5522
uuid is 5523
uuid is 5524
uuid is 5525
uuid is 5526
uuid is 5527
uuid is 5528
uuid is 5529

## Puducherry

In [96]:
Puducherry = statedic[states_list[24]]
Puducherry

Year Karaikal Pondicherry

2012    15254       51687
2013    15539       52194
2014    15754       53853
2015    15858       54218
2016    15220       54430
2017    14248       55809
2018    14729       51407
2019    15418       52731
2020   249953      234478
2021   261485      236876

In [97]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Puducherry"
    
}
Puducherry_meta = transform_data(Puducherry,doc_source)
Puducherry_meta

Year                                                 Karaikal                                        Pondicherry
Doc_Source                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People
Mode                                                 District                                           District
State                                              Puducherry                                         Puducherry

In [98]:
uuid = load_data(Puducherry,Puducherry_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5530
uuid is 5531

## Punjab

In [99]:
Punjab = statedic[states_list[25]]
Punjab

Year Amritsar Barnala Bhatinda Faridkot Fatehgarh Sahib Fazilka Ferozepur Gurdaspur Hoshiarpur Jalandhar Kapurthala Ludhiana   Mansa    Moga Mukatsar Nawanshahr Pathankot Patiala  Ropar Sangrur Sas Nagar Mohali Tarn Taran

2012    65353   25709    43407    22418           26358       0    115935     60355      71669     34331      15883    60350   36222   41534    54528      21400         0   39052  24060   46657            17485      57387
2013    66980   24693    46445    25529           28421   65662     60587     41002      73144     33599      17041    69173   41250   47499    57402      20851     16631   41336  25372   48673            17715      58294
2014    71568   28169    53041    30636           38103   79742     67830     38343      78219     33875      20653    82597   57593   54881    62613      23302     18729   72237  27925   61476            20430      66561
2015    73195   27497    54284    33974           39403   80002     69382     41133      80878     34433      21734    85190   57287   57298    65765      24594     19828   71284  29143   63287            20997      66682
2016    77542   23502    60622    38678           41187   86143     73909     44307      83038     37086      25848    93537   62221   63489    71472      26844     21187   74708  31014   70619            23586      72870
2017    82154   26249    64911    41028           44312   94068     79794     48990      86885     41473      28005   105042   65003   67227    75923      29555     23006   80899  33038   76774            26603      78776
2018   103686   31086    88252    43275           46873  105022     92196     65512      97192     54472      33316   122669   68551   76334    80783      33933     29016  102079  36526   89149            29563     100187
2019   118279   32531    93203    46645           48666  112908    105738     84701     101820     60836      37704   128613   71920   81952    88710      37064     34158  109164  39840   94114            31697     108228
2020   122830  297126   215595   446857          205264  313011     52670    139641     209212    328245     300002   209809  301655  522213   212843     435387    713804  243864  85239   89189            67298      67298
2021   125432  301331   216795   450481          208279  317236     52942    140268     210096    332936     301714   214028  303400  528820   217729     436288    721541  247222  86146   90925            68207      67655

In [100]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Punjab"
    
}
Punjab_meta = transform_data(Punjab,doc_source)
Punjab_meta

Year,Amritsar,Barnala,Bhatinda,Faridkot,Fatehgarh Sahib,Fazilka,Ferozepur,Gurdaspur,Hoshiarpur,Jalandhar,Kapurthala,Ludhiana,Mansa,Moga,Mukatsar,Nawanshahr,Pathankot,Patiala,Ropar,Sangrur,Sas Nagar Mohali,Tarn Taran
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab,Punjab

In [101]:
uuid = load_data(Punjab,Punjab_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5532
uuid is 5533
uuid is 5534
uuid is 5535
uuid is 5536
uuid is 5537
uuid is 5538
uuid is 5539
uuid is 5540
uuid is 5541
uuid is 5542
uuid is 5543
uuid is 5544
uuid is 5545
uuid is 5546
uuid is 5547
uuid is 5548
uuid is 5549
uuid is 5550
uuid is 5551
uuid is 5552
uuid is 5553

## Rajasthan

In [102]:
Rajasthan = statedic[states_list[26]]
Rajasthan

Year   Ajmer   Alwar Banswara   Baran  Barmer Bharatpur Bhilwara Bikaner   Bundi Chittorgarh   Churu   Dausa Dholpur Dungarpur Hanumangarh  Jaipur Jaisalmer  Jalore Jhalawar Jhunjhunu Jodhpur Karauli    Kota  Nagaur    Pali Pratapgarh Rajsamand Sawai Madhopur   Sikar  Sirohi Sri Ganganagar    Tonk Udaipur

2012  402293  383479   317350  227536  493834    326896   535901  344123  184203      277517  280922  344963  179305    302503      239219  497984    115315  261213   271114    149278  441464  239411  167204  470932  336009     169411    231334         229451  336456  162421         370254  266803  466109
2013  405355  387850   320949  222306  496548    327594   523260  347129  184824      274987  282971  346407  178110    305434      240338  498734    114857  261972   272479    154116  437443  238715  167465  473194  337073     169674    231187         230181  286419  162851         370618  266761  467393
2014  406982  387468   322006  212031  486253    329401   506339  345604  184648      270303  282078  345881  175790    304229      240380  494756    113956  262814   269302    156238  431246  238829  164052  471308  338160     168769    231260         229599  275454  163274         341911  265662  466521
2015  409987  392243   332063  214674  485446    337934   499681  345360  185326      269367  282195  329650  177062    308592      245215  502723    117384  264197   275430    158529  433741  243299  165118  471482  340153     170901    231164         231241  278576  164627         328866  263628  468314
2016  414540  393153   345421  216354  502476    344885   500224  348660  186549      267523  288266  319885  176793    315166      252774  503009    121850  272274   287299    161557  440991  246761  166244  471181  346167     173480    231133         237048  281757  167070         320902  266181  470151
2017  418292  325867   373812  214942  526259    343455   489294  316234  191302      252146  295847  240725  170662    321843      258056  456321    126990  263440   287821    164195  447411  243471  157706  475244  348709     174604    220517         229570  268303  161584         302076  266090  488473
2018  424196  325490   388636  217733  537613    348915   474944  318697  196984      253873  304354  230586  170975    331766      267033  459916    132180  270865   299504    165898  454461  238750  158687  483202  341891     180544    222457         228984  269571  158586         311804  263898  497383
2019  440015  335410   403467  232398  560225    357192   491608  340934  207617      258366  319148  238246  176281    345208      277142  470584    141690  283870   316987    174765  487089  246809  165247  509870  352301     194826    218850         235586  277963  165398         321854  273289  521101
2020   84157   90874    52206   94417  164183    200951   255846  235974  155020      134972  237021  483679   32786    453708      307538  191580    219537  448553   256999    377524  211499  262628  109044  239914  128165     246255    157313         149567  156962  274803         145073   14727   17942
2021   83392   91673    52705   95119  187663    237676   282560  255199  166574      149185  259021  568732   33803    492632      333483  216950    238937  465476   298394    446389  246481  293016  134141  258908  148863     277634    176081         179723  179759  304867         170286   15080   18022

In [103]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Rajasthan"
    
}
Rajasthan_meta = transform_data(Rajasthan,doc_source)
Rajasthan_meta

Year,Ajmer,Alwar,Banswara,Baran,Barmer,Bharatpur,Bhilwara,Bikaner,Bundi,Chittorgarh,Churu,Dausa,Dholpur,Dungarpur,Hanumangarh,Jaipur,Jaisalmer,Jalore,Jhalawar,Jhunjhunu,Jodhpur,Karauli,Kota,Nagaur,Pali,Pratapgarh,Rajsamand,Sawai Madhopur,Sikar,Sirohi,Sri Ganganagar,Tonk,Udaipur
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan,Rajasthan

In [104]:
uuid = load_data(Rajasthan,Rajasthan_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5554
uuid is 5555
uuid is 5556
uuid is 5557
uuid is 5558
uuid is 5559
uuid is 5560
uuid is 5561
uuid is 5562
uuid is 5563
uuid is 5564
uuid is 5565
uuid is 5566
uuid is 5567
uuid is 5568
uuid is 5569
uuid is 5570
uuid is 5571
uuid is 5572
uuid is 5573
uuid is 5574
uuid is 5575
uuid is 5576
uuid is 5577
uuid is 5578
uuid is 5579
uuid is 5580
uuid is 5581
uuid is 5582
uuid is 5583
uuid is 5584
uuid is 5585
uuid is 5586

## Sikkim

In [105]:
Sikkim = statedic[states_list[27]]
Sikkim

Year East District North District South District West District

2012         22490           6732          23283         27939
2013         23635           7121          24444         29425
2014         25711           7749          24890         29076
2015         25437           7412          24715         28377
2016         25356           7442          24891         28335
2017         21742           7643          23782         27329
2018         21934           7782          24125         27310
2019         22347           7952          24605         27756
2020        357606         348671         389637        165904
2021        417549         384187         437029        182854

In [106]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Sikkim"
    
}
Sikkim_meta = transform_data(Sikkim,doc_source)
Sikkim_meta

Year                                            East District                                     North District                                     South District                                      West District
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District
State                                                  Sikkim                                             Sikkim                                             Sikkim                                             Sikkim

In [107]:
uuid = load_data(Sikkim,Sikkim_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5587
uuid is 5588
uuid is 5589
uuid is 5590

## Tamil Nadu

In [108]:
Tamil_Nadu = statedic[states_list[28]]
Tamil_Nadu

Year Ariyalur Coimbatore Cuddalore Dharmapuri Dindigul   Erode Kanchipuram Kanniyakumari   Karur Krishnagiri Madurai Nagapattinam Namakkal Perambalur Pudukkottai Ramanathapuram   Salem Sivagangai Thanjavur The Nilgiris   Theni Thoothukkudi Tiruchirappalli Tirunelveli Tiruppur Tiruvallur Tiruvannamalai Tiruvarur Vellore Villupuram Virudhunagar

2012   182733     174580    441505     250322   270124  178393      363935         99328  149973      260130  300962       287772   179441     113873      275002         238807  362723     237701    308943        50578  128338       216847          274862      304935   219804     343343         504933    201561  454526     777355       266497
2013   206872     194330    468731     319724   291652  193162      404500        101505  163772      314301  336079       322794   211122     134140      293097         255116  389441     249313    346597        69115  137430       240150          309474      325681   240963     371588         568631    223803  518963     854956       287970
2014   193876     182258    478690     235777   294190  185310      345899         99527  155083      291108  314361       257370   210555     127026      282947         248779  405522     230338    327945        70771  137085       214292          318557      298361   196121     287643         508280    206966  461839     759879       272190
2015   179422     168169    458886     236296   296264  197242      344981         98357  146044      260252  307994       237538   207338     113578      278092         214000  414145     215452    321849        55437  138722       201154          319138      293696   198361     298178         502713    203191  453882     720936       258961
2016   187336     182142    468584     240462   309477  198592      348019         98530  148204      274439  319188       248385   220089     116854      282254         240272  437317     224906    337110        56173  139838       202969          327836      303336   201147     310214         508546    204604  463907     740177       265207
2017   169177     154008    446817     210370   301858  187050      322759         97333  130672      250138  285328       232489   226595     115935      273635         206199  429342     194781    292128        46111  132573       196081          301500      282259   181927     295176         492651    195759  421979     699284       239063
2018   170646     156340    446183     216275   309873  195042      330974        101534  135765      262092  288873       236973   223830     117828      279875         205670  426289     193090    295873        48596  133940       200235          311431      287861   188064     289424         495554    200476  417546     688446       227650
2019   174118     163869    452870     229492   321421  201494      335587        110573  142124      271450  292494       242577   228979     119994      288557         210219  437518     200838    302086        51959  136769       205385          319184      293971   200677     295478         510686    205825  425945     700223       236075
2020    12858     582529     75752     214008   419766  190300      151643        220515  201873      132206  213807       535043   383883     180405      175854         350124  101576     165393    127693       253031   56406       308823          159803       88841   286088     381223         387060    316714  166596     122173       161667
2021    15528     614621     92453     228300   476381  200477      162854        244693  211428      143452  225264       567972   414010     193529      183292         374692  108725     184923    149999       287776   60577       344085          180110      100658   299596     423069         443246    337679  195414     138255       176471

In [109]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Tamil Nadu"
    
}
Tamil_Nadu_meta = transform_data(Tamil_Nadu,doc_source)
Tamil_Nadu_meta

Year,Ariyalur,Coimbatore,Cuddalore,Dharmapuri,Dindigul,Erode,Kanchipuram,Kanniyakumari,Karur,Krishnagiri,Madurai,Nagapattinam,Namakkal,Perambalur,Pudukkottai,Ramanathapuram,Salem,Sivagangai,Thanjavur,The Nilgiris,Theni,Thoothukkudi,Tiruchirappalli,Tirunelveli,Tiruppur,Tiruvallur,Tiruvannamalai,Tiruvarur,Vellore,Villupuram,Virudhunagar
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu,Tamil Nadu

In [110]:
uuid = load_data(Tamil_Nadu,Tamil_Nadu_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5591
uuid is 5592
uuid is 5593
uuid is 5594
uuid is 5595
uuid is 5596
uuid is 5597
uuid is 5598
uuid is 5599
uuid is 5600
uuid is 5601
uuid is 5602
uuid is 5603
uuid is 5604
uuid is 5605
uuid is 5606
uuid is 5607
uuid is 5608
uuid is 5609
uuid is 5610
uuid is 5611
uuid is 5612
uuid is 5613
uuid is 5614
uuid is 5615
uuid is 5616
uuid is 5617
uuid is 5618
uuid is 5619
uuid is 5620
uuid is 5621

## Tripura

In [111]:
Tripura = statedic[states_list[29]]
Tripura

Year  Dhalai  Gomati  Khowai North Tripura Sepahijala South Tripura Unakoti West Tripura

2012   72511       0       0        115572          0        158132       0       257744
2013   78151   84987   68012         67844      92635         89210   51706       109528
2014   78575   85976   67504         68855      91462         89312   52412        95226
2015   78921   86429   67645         68669      90420         89465   52156        98210
2016   77414   86482   65891         67464      86197         88113   52133        92180
2017   78141   85619   64587         65634      84532         87785   50909        91879
2018   80536   85323   64787         66189      83847         87951   50782        92014
2019   83671   87596   66384         67536      86058         89782   51624        93844
2020  283525  135893  320240         37298     130079        376508  646676       344447
2021  319256  154430  345048         40347     145271        436936  676067       359226

In [112]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Tripura"
    
}
Tripura_meta = transform_data(Tripura,doc_source)
Tripura_meta

Year                                                   Dhalai                                             Gomati                                             Khowai                                      North Tripura                                         Sepahijala                                      South Tripura                                            Unakoti                                       West Tripura
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                                 Tripura                                            Tripura                                            Tripura                                            Tripura                                            Tripura                                            Tripura                                            Tripura                                            Tripura

In [113]:
uuid = load_data(Tripura,Tripura_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5622
uuid is 5623
uuid is 5624
uuid is 5625
uuid is 5626
uuid is 5627
uuid is 5628
uuid is 5629

## Uttar Pradesh

In [114]:

Uttar_Pradesh = statedic[states_list[30]]
Uttar_Pradesh

Year    Agra  Aligarh  Ambedkar Nagar  Amethi  Amroha  Auraiya  Ayodhya  Azamgarh  Baghpat  Bahraich  Ballia  Balrampur   Banda  Barabanki  Bareilly   Basti  Bijnor   Budaun  Bulandshahr  Chandauli  Chitrakoot  Deoria    Etah  Etawah  Farrukhabad  Fatehpur  Firozabad  Gautam Buddha Nagar  Ghaziabad  Ghazipur   Gonda  Gorakhpur  Hamirpur   Hapur  Hardoi    Hathras  Jalaun Jaunpur  Jhansi Kannauj Kanpur Dehat Kanpur Nagar Kashganj Kaushambi   Kheri Kushi Nagar Lalitpur Lucknow Maharajganj  Mahoba Mainpuri Mathura     Mau Meerut Mirzapur Moradabad Muzaffarnagar Pilibhit Pratapgarh Prayagraj Rae Bareli  Rampur Saharanpur Sambhal Sant Kabeer Nagar Sant Ravidas Nagar Shahjahanpur Shamli Shravasti Siddharth Nagar Sitapur Sonbhadra Sultanpur   Unnao Varanasi

2012  140705   151585          213765  238877  137746   123714   224072    454419    32240    348705  220486     159894  196329     399167    230993  272081  171468   251172       107245     243544      117549  179181  127567  131077       121111    231307      89065                27376      31602    280716  249421     332822    157262       0  473310      73330  187949  284583  168296  114482       206613       212437   136806    173914  428178      432547   205377  219716      270890   95295   183737   99644  208398  32735   291071    188148         65264   281930     237208    337547     216562  123776     139859       0            243134             116147       266103      0    139611          272008  545270    324148    196004  396218   138024
2013  139063   158508          220856  196020  140262   127047   229858    432006    34892    358856  224317     163206  201062     426074    228082  277958  177607   220588       114529     243226      119121  190850  125566  132174       123833    236213      88607                28992      15843    284955  255016     330047    161175   19720  479537      76153  190510  295536  168128  116035       209669       214147   134035    176753  439345      419647   198568  204036      277929   97333   185667  103462  212451  35672   289358    125091         52618   291514     243681    343346     274016  129977     142319  116691            215133             120097       269379  19799    145339          278273  544721    320844    199197  401652   142158
2014  138759   163054          222929  198634  140875   123745   211179    401032    39784    363584  232175     163036  201912     421794    231603  272535  179153   222150       117271     229661      116835  195389  126603  126740       125222    237719      88723                31096      18241    284389  260421     309144    160685   19859  486077      79827  187481  299839  169345  118694       206317       208920   123970    177781  445478      382429   164323  185236      268293   96893   192067  104646  210109  40441   283914    124182         67285   267713     254295    350657     274947  134063     144495  118582            211561             122546       271238  22521    123594          274940  532117    318843    198702  395192   146963
2015  151686   168810          226575  207677  150861   128488   220993    407274    43701    386236  256026     167483  205967     427785    239305  279734  187833   229289       116224     234227      121553  201582  130277  129113       130460    251775     100640                30613      19702    303633  274869     323706    160794   24087  510349      81580  194436  308107  172914  125210       211527       212911   126091    179436  470951      382375   171457  178341      283161  100790   192912  107142  222099  47948   292511    127949         77031   273043     271010    365887     294612  139275     143362  124090            221395             125819       282720  26797    132830          289868  555215    326209    212514  391324   151726
2016  154914   184789          242747  213653  163540   124735   231145    425464    41357    424955  279702     189847  215060     445635    258068  322651  206585   259326       105547     239503      128048  224532  138131  133651       142782    271679     120072                29191      19429    324223  307423     350303    166585   17013  562388      82261  208959  348293  184398  137175       214809       213313   127715    192172  510192      394484   183083  175098      303845  106470   192225  115738  236661  51054   294930    148504         83202   287528     307790    388350     302521  160192     105870  150581            243419             129636       304364  28352    138166          342097  598151    331935    240613  388853   157901
2017  148211   174977          226190  199466  152744   124563   211650    408492    31502    380307  274889     170901  195103     425136    243919  316731  196445   234425       100446     226151      118712  210730  129754  132329       136347    257248     121638                15179      18794    321589  279944     352325    153975    9827  542954      72874  199628  329681  170864  140090       203303       199461   124387    194310  484161      372852   161577  170154      295983   94573   142400  120187  227511  48723   275708    143347         76035   267834     304688    338221     291880  149993     110157  137928            247500             124014       294494  29349    116607          323069  582222    326337    241952  341736   149636
2018  151928   185301          232620  208664  143868   124801   217252    429708    31754    402774  280465     175785  201437     429074    250064  333772  194852   240659       102778     224850      120089  224243  140650  137916       143375    248696     125674                14278      17918    319313  296454     358982    155587   10328  543417      70898  199494  345928  177002  142704       205142       197339   125504    197455  495874      357037   166053  170037      296813   95996   150552  121500  225137  46473   280749    146704         78882   263998     326982    354992     294620  152704     112932  144208            252363             126051       296743  31545    120911          343709  598211    329314    263380  348331   151223
2019  157625   193396          243174  221703  150120   129801   227946    454137    32116    434222  291986     182895  211051     438552    255589  354955  205584   252627       106161     229685      124700  234146  148928  143069       150593    263334     136036                14434      17916    335021  329737     373057    159803   11875  558620      72478  208156  375951  184183  149573       212516       199994   128564    201510  513187      371136   173522  172594      316604   98140   156754  122461  236523  50964   293002    152545         85264   271788     355759    364948     303220  159747     117573  150830            268881             130418       306755  34321    126356          364636  620376    337616    279967  360090   155403
2020  304078   372226          159967  101798   46244    73137    32949     61810   177086     59287   98421      67394   49195     154660    111504   84511  751615  1142023       616158     722164      618474  125180  269144  487244       744471    281917     432319               741515    1226931    721834  136808     759942    812663  519623   98811  135164939
2021  336223   398917          176915  104289   47719    74740    34949     64139   180422     61232  101997      69151   50519     158431    116331   87085  782372  1233846       636658     743706      623242  127528  274394  502229       794464    321147     433682               773016    1273037    731423  139238     802564    837695  531395  100336  140995574

In [115]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Uttar Pradesh"
    
}
Uttar_Pradesh_meta = transform_data(Uttar_Pradesh,doc_source)
Uttar_Pradesh_meta

Year,Agra,Aligarh,Ambedkar Nagar,Amethi,Amroha,Auraiya,Ayodhya,Azamgarh,Baghpat,Bahraich,Ballia,Balrampur,Banda,Barabanki,Bareilly,Basti,Bijnor,Budaun,Bulandshahr,Chandauli,Chitrakoot,Deoria,Etah,Etawah,Farrukhabad,Fatehpur,Firozabad,Gautam Buddha Nagar,Ghaziabad,Ghazipur,Gonda,Gorakhpur,Hamirpur,Hapur,Hardoi,Hathras,Jalaun,Jaunpur,Jhansi,Kannauj,Kanpur Dehat,Kanpur Nagar,Kashganj,Kaushambi,Kheri,Kushi Nagar,Lalitpur,Lucknow,Maharajganj,Mahoba,Mainpuri,Mathura,Mau,Meerut,Mirzapur,Moradabad,Muzaffarnagar,Pilibhit,Pratapgarh,Prayagraj,Rae Bareli,Rampur,Saharanpur,Sambhal,Sant Kabeer Nagar,Sant Ravidas Nagar,Shahjahanpur,Shamli,Shravasti,Siddharth Nagar,Sitapur,Sonbhadra,Sultanpur,Unnao,Varanasi
Doc_Source,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal,MNREGA Portal
Path,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...,Schemes/MNREGA/Total households applied for jo...
Units,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People,Number of People
Mode,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District,District
State,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh,Uttar Pradesh

In [116]:
uuid = load_data(Uttar_Pradesh,Uttar_Pradesh_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5630
uuid is 5631
uuid is 5632
uuid is 5633
uuid is 5634
uuid is 5635
uuid is 5636
uuid is 5637
uuid is 5638
uuid is 5639
uuid is 5640
uuid is 5641
uuid is 5642
uuid is 5643
uuid is 5644
uuid is 5645
uuid is 5646
uuid is 5647
uuid is 5648
uuid is 5649
uuid is 5650
uuid is 5651
uuid is 5652
uuid is 5653
uuid is 5654
uuid is 5655
uuid is 5656
uuid is 5657
uuid is 5658
uuid is 5659
uuid is 5660
uuid is 5661
uuid is 5662
uuid is 5663
uuid is 5664
uuid is 5665
uuid is 5666
uuid is 5667
uuid is 5668
uuid is 5669
uuid is 5670
uuid is 5671
uuid is 5672
uuid is 5673
uuid is 5674
uuid is 5675
uuid is 5676
uuid is 5677
uuid is 5678
uuid is 5679
uuid is 5680
uuid is 5681
uuid is 5682
uuid is 5683
uuid is 5684
uuid is 5685
uuid is 5686
uuid is 5687
uuid is 5688
uuid is 5689
uuid is 5690
uuid is 5691
uuid is 5692
uuid is 5693
uuid is 5694
uuid is 5695
uuid is 5696
uuid is 5697
uuid is 5698
uuid is 5699
uuid is 5700
uuid is 5701
uuid is 5702
uuid is 5703
uuid is 5704

## Uttarakhand

In [117]:
Uttarakhand = statedic[states_list[31]]
Uttarakhand

Year  Almora Bageshwar Chamoli Champawat Dehradun Haridwar Nainital Pauri Garhwal Pithoragarh Rudra Prayag Tehri Garhwal Udam Singh Nagar Uttar Kashi

2012  101530     46084   81060     39763    65333   118123    41479        110728       87235        44029        144685            83571       74320
2013  102435     47732   83004     40740    66392   124656    43263        112712       89997        46012        148690            85366       75327
2014  102729     46461   83379     41119    67354   131469    45024        114553       91619        49219        151130            86083       75778
2015  103997     48131   82719     36926    72722   135341    47261        117366       88152        51136        158337            92612       81625
2016  103391     49983   83685     37687    78448   146183    52325        118549       87903        52580        162964            95323       84557
2017   99475     47348   68076     32492    73831   146352    50100        113829       75602        47304        150413            93769       81071
2018   99316     47212   70052     32950    61544   159731    55024         97695       64624        47377        150761            98514       81619
2019  100013     47350   71809     32187    61444   169338    58248         99357       63572        48492        152030           102865       82967
2020
2021

In [118]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"Uttarakhand"
    
}
Uttarakhand_meta = transform_data(Uttarakhand,doc_source)
Uttarakhand_meta

Year                                                   Almora                                          Bageshwar                                            Chamoli                                          Champawat                                           Dehradun                                           Haridwar                                           Nainital                                      Pauri Garhwal                                        Pithoragarh                                       Rudra Prayag                                      Tehri Garhwal                                   Udam Singh Nagar                                        Uttar Kashi
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                             Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand                                        Uttarakhand

In [119]:
uuid = load_data(Uttarakhand,Uttarakhand_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5705
uuid is 5706
uuid is 5707
uuid is 5708
uuid is 5709
uuid is 5710
uuid is 5711
uuid is 5712
uuid is 5713
uuid is 5714
uuid is 5715
uuid is 5716
uuid is 5717

## West Bengal

In [120]:
West_Bengal = statedic[states_list[32]]
West_Bengal

Year 24 Parganas (North) 24 Parganas South Bankura Birbhum Coochbehar Darjeeling Gorkha Hill Council (Dghc) Dinajpur Dakshin Dinajpur Uttar Hooghly  Howrah Jalpaiguri  Maldah Murshidabad   Nadia Paschim Bardhaman Paschim Medinipur Purba Medinipur Purulia Siliguri Mahakuma Parisad

2012              741737            822194  579173  658227     602112                                135800           302916         441126  640324  232894     649394  597571     1037679  713084            993107            874923          670770  446947                     86873
2013              750023            850196  589898  663344     606220                                139366           310438         443122  669042  240199     665732  609876     1069283  718153           1038436            898113          685931  456861                     91666
2014              756943            893918  600422  668790     623922                                145586           321843         453608  684104  245038     689170  643163     1139188  726323           1062029            921649          707296  469053                     96178
2015              772142            945261  613357  681331     648885                                150105           335350         476571  704016  253209     714521  671114     1179402  735077           1072568            944010          727831  479954                     99874
2016              785665           1030745  622829  687576     671410                                154647           349721         505838  719612  268942     423213  710838     1203679  739268           1080300            964128          742591  488525                    101770
2017              804962           1098746  632537  693658     688693                                160716           357762         524762  739416  291777     420560  740514     1230019  747364           1071104            976011          758838  497750                    104666
2018              707299            978634  601962  682535     599881                                114528           289450         439032  727896  241265     414891  604340     1143883  705683            131662            726728          773259  499683                     96516
2019              718145           1027015  601385  688066     608386                                121517           256354         460639  734319  258503     427253  658399     1154373  708611            133788            736253          782936  505141                     97452
2020
2021

In [121]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"West Bengal"
    
}
West_Bengal_meta = transform_data(West_Bengal,doc_source)
West_Bengal_meta

Year                                      24 Parganas (North)                                  24 Parganas South                                            Bankura                                            Birbhum                                         Coochbehar              Darjeeling Gorkha Hill Council (Dghc)                                   Dinajpur Dakshin                                     Dinajpur Uttar                                            Hooghly                                             Howrah                                         Jalpaiguri                                             Maldah                                        Murshidabad                                              Nadia                                  Paschim Bardhaman                                  Paschim Medinipur                                    Purba Medinipur                                            Purulia                          Siliguri Mahakuma Parisad
Doc_Source                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...  Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People                                   Number of People
Mode                                                 District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District                                           District
State                                             West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal                                        West Bengal

In [122]:
uuid = load_data(West_Bengal,West_Bengal_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5718
uuid is 5719
uuid is 5720
uuid is 5721
uuid is 5722
uuid is 5723
uuid is 5724
uuid is 5725
uuid is 5726
uuid is 5727
uuid is 5728
uuid is 5729
uuid is 5730
uuid is 5731
uuid is 5732
uuid is 5733
uuid is 5734
uuid is 5735
uuid is 5736

## All India

In [123]:
All_India = statedic[states_list[33]]
All_India = All_India.rename(columns={All_India.columns[0]:"All Districts"})
All_India

Year All Districts

2012     122641399
2013     127736953
2014     125447824
2015     124489895
2016     127746183
2017     125598201
2018     126282744
2019     129653358
2020
2021

In [124]:

doc_source={
    "Doc_Source":"MNREGA Portal",
    "Path":PATH,
    "Units":"Number of People",
    "Mode":"District",
    "State":"All India"
    
}
All_India_meta = transform_data(All_India,doc_source)
All_India_meta

Year                                            All Districts
Doc_Source                                      MNREGA Portal
Path        Schemes/MNREGA/Total households applied for jo...
Units                                        Number of People
Mode                                                 District
State                                               All India

In [125]:
uuid = load_data(All_India,All_India_meta,INDEX_NAME,TYPE_NAME,uuid )

uuid is 5737