In [30]:
import os
os.getcwd()

'C:\\Users\\Abhishek\\Documents\\Athasastra\\manrega'

In [37]:
df_state[0][9]

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,NaN,NaN,MGNREGA Public Data Portal For FY: 2020-2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Sno.State NameTotal households applied for job...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sno.,State Name,Total households applied for job card,Total job cards issued,Total job cards (SC),Total job cards (ST),Total job cards (non-SC/ST),Total households demanded work,Total persons demanded work,Total households allotted work,...,Amount sanctioned (Rs. In Lakhs),Total works,Total bank accounts,Total individual bank accounts,Total joint bank accounts,Amount disbursed to bank accounts,Total post office accounts,Total individual post office accounts,Total joint post office accounts,Amount disbursed to post office accounts
5,1,NAGALAND,444630,440121,3719,418919,17483,390995,414827,390026,...,5714294,38369,204340,201383,2957,713207657,207,207,0,966384
6,2,ANDHRA PRADESH,9383686,9383686,2240169,747102,6396415,5018766,8775945,5012302,...,5505422,5713865,9166453,9166102,351,41222413024,502151,502151,0,180777905
7,3,ARUNACHAL PRADESH,257774,250018,256,230446,19316,214271,228546,213322,...,9724580,15705,277254,257725,19529,2831564427,1926,1918,8,23648
8,4,ASSAM,5511384,5001228,271005,747123,3983100,1853550,2630096,1852388,...,7765466,837425,6023576,5690993,332583,9076308045,332665,315863,16802,24181344
9,5,BIHAR,19754516,17813405,3830125,280562,13702718,4836845,5648953,4824866,...,101010410,3557149,10072169,9448558,623611,28230299660,3002,2910,92,784176
10,6,CHHATTISGARH,4230237,3991993,425070,1284205,2282718,3087326,6300308,3086874,...,3554793,1373091,7758066,7701925,56141,18072275750,165192,163696,1496,239538879
11,7,GOA,37661,33867,795,9965,23107,3536,3683,3463,...,77260,3747,20416,20167,249,10341088,5,5,0,0
12,8,GUJARAT,4131575,3975001,248720,1504500,2221781,1224226,2229041,1221958,...,22315508,500960,3651362,3239819,411543,6504562296,549935,369898,180037,4288431
13,9,HARYANA,1091513,1090067,437683,208,652176,454967,675505,454291,...,763021,121472,1318441,1272181,46260,3522053060,39017,36003,3014,306758476
14,10,HIMACHAL PRADESH,1351981,1316370,344597,81873,889900,614403,857316,614221,...,2403362,430518,1589968,1540252,49716,5052559393,8002,7842,160,4418944
15,11,JAMMU AND KASHMIR,1308133,1208462,78256,135461,994745,525911,777803,524631,...,10184075,399204,1787506,1781516,5990,6992768520,496,488,8,0
16,12,JHARKHAND,5937321,5181767,562087,1609307,3010373,2588034,3548618,2586330,...,8086135,2239963,5189020,5121030,67990,14333335851,499148,424160,74988,18849
17,13,KARNATAKA,6885929,6879005,1242060,618176,5018769,2957856,5718629,2904524,...,59801244,2797829,11479642,10859513,620129,29751171900,235470,128945,106525,3095
18,14,KERALA,3800083,3776198,451267,126095,3198836,1597763,1855161,1597570,...,1097896,1813731,3577703,3567198,10505,17947382729,43901,43845,56,53458463
19,15,MADHYA PRADESH,8093351,7470220,1173218,2385431,3911571,5398448,10627681,5391750,...,125906655,2102722,10799165,9188496,1610669,38148168547,244016,195491,48525,513023128
20,16,MAHARASHTRA,9597805,8812829,834381,1221638,6756810,1455847,2792633,1452141,...,127016639,1514849,7403212,6814191,589021,8839993327,1196930,1168862,28068,66816608
21,17,MANIPUR,579438,575449,15013,245898,314538,532756,585310,531960,...,171483,138906,602793,562471,40322,3816667941,18318,16136,2182,205167
22,18,MEGHALAYA,614995,603035,4020,555872,43143,482201,653467,482081,...,2444823,123494,580206,459708,120498,3440440433,4104,3853,251,1780498
23,19,MIZORAM,203933,203336,39,201572,1725,212065,220479,211599,...,48767,57183,209064,204677,4387,3447178356,0,0,0,0
24,20,ODISHA,7487134,7213802,1213491,1952930,4047381,3708498,6761342,3706238,...,27906633,2245867,9281299,8888414,392885,29470719910,679118,519274,159844,458990697
25,21,PUDUCHERRY,73591,71682,19990,130,51562,53951,62407,53948,...,3757,3493,93829,93352,477,224703753,249,249,0,0
26,22,PUNJAB,1953128,1817142,1192971,867,623304,932228,1170075,931222,...,327156,351334,2108652,2034932,73720,6177247410,36442,35232,1210,439952
27,23,RAJASTHAN,11463482,11027111,2223021,2075565,6728525,7423880,11081236,7421656,...,13816793,1903105,15649558,15285827,363731,53379455967,816119,789396,26723,286211
28,24,SIKKIM,85771,84593,3914,31087,49592,62919,73750,62852,...,344443,24312,111823,110503,1320,537233758,883,839,44,0
29,25,TAMIL NADU,8901751,8639754,2187401,128674,6323679,6534129,7745476,6533797,...,1802368,1602384,10611745,10605504,6241,44859562409,17,17,0,27218
30,26,TRIPURA,642144,637134,109532,261787,265815,582771,794948,582761,...,148158,951772,1086304,1077976,8328,5572512106,78,61,17,12836
31,27,UTTAR PRADESH,21343779,19033181,5847585,177757,13007839,11098974,14251188,11093714,...,67620928,3413642,19665591,19268070,397521,59514952518,232358,220834,11524,308937
32,28,UTTARAKHAND,1212519,1150616,210805,41939,897872,609425,835846,609170,...,194632,280758,1416894,1369877,47017,3979354502,30395,29556,839,41200314
33,29,WEST BENGAL,13741151,13039281,3279237,912649,8847395,7675604,11594411,7674239,...,12399901,5798283,19733235,18569509,1163726,58643299905,1197414,1097098,100316,45079866
34,NaN,Total:,150120395,140720353,28450427,17987738,94282188,72132145,108914680,72025894,...,618156601,40355132,161469286,154401869,7067417,504311734242,6837558,6074829,762729,1943390026
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Note: Figures shown above are indicative only ...,Note: Figures shown above are indicative only ...,Note: Figures shown above are indicative only ...,Note: Figures shown above are indicative only ...,Note: Figures shown above are indicative only ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
import time
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
driver = webdriver.Chrome(executable_path="C:\Drivers\chromedriver")
driver.get("https://nregarep2.nic.in/netnrega/dynamic2/DynamicReport_new4.aspx")
from selenium.webdriver.common.action_chains import ActionChains
#driver.maximize_window()
driver.implicitly_wait(10)
wait = WebDriverWait(driver, 10)
import select as select
time.sleep(5) 


check_list = ['ChkLstFieldsWorkerA_0', 'ChkLstFieldsWorkerA_1','ChkLstFieldsWorkerA_2','ChkLstFieldsWorkerA_3','ChkLstFieldsWorkerA_4',
             'ChkLstFieldsWorkerC_0', 'ChkLstFieldsWorkerC_1', 'ChkLstFieldsWorkerD_0', 'ChkLstFieldsWorkerD_1',
              'ChkLstFieldsWorkerE_0','ChkLstFieldsWorkerE_1','ChkLstFieldsWorkerE_2','ChkLstFieldsWorkerE_3',
              'ChkLstFieldsWorkerE_4','ChkLstFieldsWorkerE_5','ChkLstFieldsWorkerE_6', 
             'ChkLstFieldsWorkerE_7','ChkLstFieldsWorkerE_8','ChkLstFieldsWorkerE_9','ChkLstFieldsWorkerE_10',
              'ChkLstFieldsWorkerE_11','ChkLstFieldsWorkerE_12','ChkLstFieldsWorkerE_13',
              'CTxtBox1', 'CTxtBox2', 
             'ChkLstFieldsWork_0', 'ChkLstFieldsWork_1','ChkLstFieldsWork_2','ChkLstFieldsWork_3',
             'ChkLstFieldsWork_W_0','ChkLstFieldsWork_W_1',
             'ChkBox1','ChkBox2','ChkBox4',
             'CTxtBox3','CTxtBox4','CTxtBox5','CTxtBox6','CTxtBox7','CTxtBox8','CTxtBox9','CTxtBox10']

year_slct = ['2011-2012', '2012-2013','2013-2014','2014-2015','2015-2016','2016-2017','2017-2018','2018-2019','2019-2020','2020-2021']

lod_slct = ['State', 'District']

total_hh = ['1-10', '11-20', '21-30', '31-40', '41-50', '51-60','61-70', '71-80', '81-99', '100', '>100', '>14']
total_worker_age = ['18-30 yrs','30-40 yrs','40-50 yrs','50-60 yrs','>60 yrs']
months = ['April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January','February', 'March']
rem_check = ['TxtBox1', 'TxtBox9', 'TxtBox5', 'TxtBox6', 'TxtBox7', 'TxtBox8']
drp_box = ['DdlstTxtBox1', 'DdlstTxtBox9','DdlstTxtBox5','DdlstTxtBox6','DdlstTxtBox7','DdlstTxtBox8']


def slct_indicators():
    for i in check_list:
        checkboxes = driver.find_elements_by_id(i)
        for checkbox in checkboxes:
            while not checkbox.is_selected():
                checkbox.click()

def slct_state():
    lod_element = driver.find_element_by_id('regionselect')
    lod_drp = Select(lod_element)
    lod_drp.select_by_visible_text('State')
    driver.find_element_by_xpath("//*[@id='checklist']/ul/li/label/input").click()


def slct_district():
    lod_element = driver.find_element_by_id('regionselect')
    lod_drp = Select(lod_element)
    lod_drp.select_by_visible_text('District')
    driver.find_element_by_xpath("//*[@id='checklist']/ul/li/label/input").click()


def slct_block():
    lod_element = driver.find_element_by_id('regionselect')
    lod_drp = Select(lod_element)
    lod_drp.select_by_visible_text('Block')
    driver.find_element_by_xpath("//*[@id='checklist']/ul/li/label/input").click()



# State wise remaining indicators
#Total households completed person-days in range
total_hh_completed_person_days_st=[]
for i in year_slct:    
    for l in total_hh:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_state()

        driver.find_element_by_id('TxtBox1').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox1')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_hh_completed_person_days_st.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_hh_completed_person_days_st = pd.DataFrame(total_hh_completed_person_days_st)
df_total_hh_completed_person_days_st.to_csv('df_total_hh_completed_person_days_st.csv')

#total workers employed in age group
total_workers_employed_st=[]
for i in year_slct:    
    for l in total_worker_age:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_state()

        driver.find_element_by_id('TxtBox9').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox9')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_workers_employed_st.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_workers_employed_st = pd.DataFrame(total_workers_employed_st)
df_total_workers_employed_st.to_csv('df_total_workers_employed_st.csv')



#Total_hh_demanded_work
total_hh_demanded_work_st=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_state()

        driver.find_element_by_id('TxtBox5').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox5')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_hh_demanded_work_st.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_hh_demanded_work_st = pd.DataFrame(total_hh_demanded_work_st)
df_total_hh_demanded_work_st.to_csv('df_total_hh_demanded_work_st.csv')

#total_persons_demanded_work
total_persons_demanded_work_st=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_state()

        driver.find_element_by_id('TxtBox6').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox6')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_persons_demanded_work_st.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_persons_demanded_work_st = pd.DataFrame(total_persons_demanded_work_st)
df_total_persons_demanded_work_st.to_csv('df_total_persons_demanded_work_st.csv')

#total_hh_worked
total_hh_worked_st=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_state()

        driver.find_element_by_id('TxtBox7').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox7')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_hh_worked_st.append(table)
        driver.find_element_by_id("BtnBack").click()
df_total_hh_worked_st = pd.DataFrame(total_hh_worked_st)
df_total_hh_worked_st.to_csv('df_total_hh_worked_st.csv')

#total_persons_worked
total_persons_worked_st=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_state()

        driver.find_element_by_id('TxtBox8').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox8')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_persons_worked_st.append(table)
        driver.find_element_by_id("BtnBack").click()

df_total_persons_worked_st = pd.DataFrame(total_persons_worked_st)
df_total_persons_worked_st.to_csv('df_total_persons_worked_st.csv')

# district wise remaining indicators
#Total households completed person-days in range
total_hh_completed_person_days_dt=[]
for i in year_slct:    
    for l in total_hh:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_district()

        driver.find_element_by_id('TxtBox1').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox1')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_hh_completed_person_days_dt.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_hh_completed_person_days_dt = pd.DataFrame(total_hh_completed_person_days_dt)
df_total_hh_completed_person_days_dt.to_csv('df_total_hh_completed_person_days_dt.csv') 



#total workers employed in age group
total_workers_employed_dt=[]
for i in year_slct:    
    for l in total_worker_age:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_district()

        driver.find_element_by_id('TxtBox9').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox9')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_workers_employed_dt.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_workers_employed_dt = pd.DataFrame(total_workers_employed_dt)
df_total_workers_employed_dt.to_csv('df_total_workers_employed_dt.csv')



#Total_hh_demanded_work
total_hh_demanded_work_dt=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_district()

        driver.find_element_by_id('TxtBox5').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox5')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_hh_demanded_work_dt.append(table)
        driver.find_element_by_id("BtnBack").click()

df_total_hh_demanded_work_dt = pd.DataFrame(total_hh_demanded_work_dt)
df_total_hh_demanded_work_dt.to_csv('df_total_hh_demanded_work_dt.csv')

#total_persons_demanded_work
total_persons_demanded_work_dt=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_district()

        driver.find_element_by_id('TxtBox6').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox6')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_persons_demanded_work_dt.append(table)
        driver.find_element_by_id("BtnBack").click()
df_total_persons_demanded_work_dt = pd.DataFrame(total_persons_demanded_work_dt)
df_total_persons_demanded_work_dt.to_csv('df_total_persons_demanded_work_dt.csv')

#total_hh_worked
total_hh_worked_dt=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_district()

        driver.find_element_by_id('TxtBox7').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox7')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_hh_worked_dt.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_hh_worked_dt = pd.DataFrame(total_hh_worked_dt)
df_total_hh_worked_dt.to_csv('df_total_hh_worked_dt.csv')

#total_persons_worked
total_persons_worked_dt=[]
for i in year_slct:    
    for l in months:

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        slct_district()

        driver.find_element_by_id('TxtBox8').click()

        drp_ele = driver.find_element_by_id('DdlstTxtBox8')
        drp = Select(drp_ele)
        drp.select_by_visible_text(l)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(2) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        total_persons_worked_tt.append(table)
        driver.find_element_by_id("BtnBack").click()
        
df_total_persons_worked_dt = pd.DataFrame(total_persons_worked_dt)
df_total_persons_worked_dt.to_csv('df_total_persons_worked_dt.csv')

driver.quit()

ValueError: No tables found

In [29]:
state_table

NameError: name 'state_table' is not defined

In [26]:
df_state = pd.DataFrame(state_table)
df_state.to_csv('df_state.csv') 

df_district = pd.DataFrame(district_table)
df_district.to_csv('df_district.csv')

df_block = pd.DataFrame(block_table)
df_block.to_csv('df_block.csv')

NameError: name 'state_table' is not defined

In [27]:
df_total_hh_completed_person_days_st = pd.DataFrame(total_hh_completed_person_days_st)
df_total_hh_completed_person_days_st.to_csv('./df_total_hh_completed_person_days_st.csv') 



df_total_hh_demanded_work_st = pd.DataFrame(total_hh_demanded_work_st)
df_total_hh_demanded_work_st.to_csv('./df_total_hh_demanded_work_st.csv')

NameError: name 'total_hh_completed_person_days_st' is not defined

In [28]:
df_total_hh_completed_person_days_dt = pd.DataFrame(total_hh_completed_person_days_dt)
df_total_hh_completed_person_days_dt.to_csv('df_total_hh_completed_person_days_dt.csv') 


df_total_hh_demanded_work_dt = pd.DataFrame(total_hh_demanded_work_dt)
df_total_hh_demanded_work_dt.to_csv('df_total_hh_demanded_work_dt.csv')

NameError: name 'total_hh_completed_person_days_dt' is not defined

In [ ]:
df_total_hh_completed_person_days_bl = pd.DataFrame(total_hh_completed_person_days_bl)
df_total_hh_completed_person_days_bl.to_csv('df_total_hh_completed_person_days_bl.csv') 



df_total_hh_demanded_work_bl = pd.DataFrame(total_hh_demanded_work_bl)
df_total_hh_demanded_work_bl.to_csv('df_total_hh_demanded_work_bl.csv')

In [ ]:
import time
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
#driver = webdriver.Chrome(executable_path="C:\Drivers\chromedriver")
#driver.get("https://nregarep2.nic.in/netnrega/dynamic2/DynamicReport_new4.aspx")
from selenium.webdriver.common.action_chains import ActionChains
#driver.maximize_window()
#driver.implicitly_wait(10)
#wait = WebDriverWait(driver, 10)
import select as select
#time.sleep(5) 

def get_manrega_df( driver, download_dir, countrycode, hslevelcode, currency):
    url = 'https://nregarep2.nic.in/netnrega/dynamic2/DynamicReport_new4.aspx'      #Url need to scrape data from
    driver.get(url)                                                 #Initializing driver with the url
    driver.implicitly_wait(10)

    check_list = ['ChkLstFieldsWorkerA_0', 'ChkLstFieldsWorkerA_1','ChkLstFieldsWorkerA_2','ChkLstFieldsWorkerA_3','ChkLstFieldsWorkerA_4',
                 'ChkLstFieldsWorkerC_0', 'ChkLstFieldsWorkerC_1', 'ChkLstFieldsWorkerD_0', 'ChkLstFieldsWorkerD_1',
                  'ChkLstFieldsWorkerE_0','ChkLstFieldsWorkerE_1','ChkLstFieldsWorkerE_2','ChkLstFieldsWorkerE_3',
                  'ChkLstFieldsWorkerE_4','ChkLstFieldsWorkerE_5','ChkLstFieldsWorkerE_6', 
                 'ChkLstFieldsWorkerE_7','ChkLstFieldsWorkerE_8','ChkLstFieldsWorkerE_9','ChkLstFieldsWorkerE_10',
                  'ChkLstFieldsWorkerE_11','ChkLstFieldsWorkerE_12','ChkLstFieldsWorkerE_13',
                  'CTxtBox1', 'CTxtBox2', 
                 'ChkLstFieldsWork_0', 'ChkLstFieldsWork_1','ChkLstFieldsWork_2','ChkLstFieldsWork_3',
                 'ChkLstFieldsWork_W_0','ChkLstFieldsWork_W_1',
                 'ChkBox1','ChkBox2','ChkBox4',
                 'CTxtBox3','CTxtBox4','CTxtBox5','CTxtBox6','CTxtBox7','CTxtBox8','CTxtBox9','CTxtBox10']

    year_slct = ['2011-2012', '2012-2013','2013-2014','2014-2015','2015-2016','2016-2017','2017-2018','2018-2019','2019-2020','2020-2021']

    lod_slct = ['State', 'District', 'Block']

    total_hh = ['1-10', '11-20', '21-30', '31-40', '41-50', '51-60','61-70', '71-80', '81-99', '100', '>100', '>14']
    total_worker_age = ['18-30 yrs','30-40 yrs','40-50 yrs','50-60 yrs','>60 yrs']
    months = ['April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'January','February', 'March']
    rem_check = ['TxtBox1', 'TxtBox9', 'TxtBox5', 'TxtBox6', 'TxtBox7', 'TxtBox8']
    drp_box = ['DdlstTxtBox1', 'DdlstTxtBox9','DdlstTxtBox5','DdlstTxtBox6','DdlstTxtBox7','DdlstTxtBox8']


    def slct_indicators():
        for i in check_list:
            checkboxes = driver.find_elements_by_id(i)
            for checkbox in checkboxes:
                while not checkbox.is_selected():
                    checkbox.click()

    def slct_state():
        lod_element = driver.find_element_by_id('regionselect')
        lod_drp = Select(lod_element)
        lod_drp.select_by_visible_text('State')
        driver.find_element_by_xpath("//*[@id='checklist']/ul/li/label/input").click()


    def slct_district():
        lod_element = driver.find_element_by_id('regionselect')
        lod_drp = Select(lod_element)
        lod_drp.select_by_visible_text('District')
        driver.find_element_by_xpath("//*[@id='checklist']/ul/li/label/input").click()


    def slct_block():
        lod_element = driver.find_element_by_id('regionselect')
        lod_drp = Select(lod_element)
        lod_drp.select_by_visible_text('Block')
        driver.find_element_by_xpath("//*[@id='checklist']/ul/li/label/input").click()

    state_table=[]
    for i in year_slct:
        slct_indicators()
        slct_state()

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(5) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        state_table.append(table)
        driver.find_element_by_id("BtnBack").click()

    district_table=[]
    for i in year_slct:
        slct_indicators()
        slct_district()

        year_element = driver.find_element_by_id("DdlstFinYear")
        year_drp = Select(year_element)
        year_drp.select_by_visible_text(i)

        driver.find_element_by_id("viewDummy").click()
        time.sleep(10) 

        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        div=soup.select_one("div#content")
        table=pd.read_html(str(div))
        district_table.append(table)
        driver.find_element_by_id("BtnBack").click()

    block_table=[] 
    for i in check_list:
        for p in year_slct:
            driver.find_element_by_id(i).click()
            slct_block()

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(p)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(5)

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            block_table.append(table)
            driver.find_element_by_id("BtnBack").click()

    '''df_state = pd.DataFrame(state_table)
    df_state.to_csv('df_state.csv') 

    df_district = pd.DataFrame(district_table)
    df_district.to_csv('df_district.csv')

    df_block = pd.DataFrame(block_table)
    df_block.to_csv('df_block.csv')'''

    # State wise remaining indicators
    #Total households completed person-days in range
    total_hh_completed_person_days_st=[]
    for i in year_slct:    
        for l in total_hh:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_state()

            driver.find_element_by_id('TxtBox1').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox1')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_completed_person_days_st.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total workers employed in age group
    total_workers_employed_st=[]
    for i in year_slct:    
        for l in total_worker_age:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_state()

            driver.find_element_by_id('TxtBox9').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox9')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_workers_employed_st.append(table)
            driver.find_element_by_id("BtnBack").click()

    #Total_hh_demanded_work
    total_hh_demanded_work_st=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_state()

            driver.find_element_by_id('TxtBox5').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox5')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_demanded_work_st.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_persons_demanded_work
    total_persons_demanded_work_st=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_state()

            driver.find_element_by_id('TxtBox6').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox6')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_persons_demanded_work_st.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_hh_worked
    total_hh_worked_st=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_state()

            driver.find_element_by_id('TxtBox7').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox7')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_worked_st.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_persons_worked
    total_persons_worked_st=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_state()

            driver.find_element_by_id('TxtBox8').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox8')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_persons_worked_st.append(table)
            driver.find_element_by_id("BtnBack").click()


    '''df_total_hh_completed_person_days_st = pd.DataFrame(total_hh_completed_person_days_st)
    df_total_hh_completed_person_days_st.to_csv('df_total_hh_completed_person_days_st.csv') 

    df_total_workers_employed_st = pd.DataFrame(total_workers_employed_st)
    df_total_workers_employed_st.to_csv('df_total_workers_employed_st.csv')

    df_total_hh_demanded_work_st = pd.DataFrame(total_hh_demanded_work_st)
    df_total_hh_demanded_work_st.to_csv('df_total_hh_demanded_work_st.csv')

    df_total_persons_demanded_work_st = pd.DataFrame(total_persons_demanded_work_st)
    df_total_persons_demanded_work_st.to_csv('df_total_persons_demanded_work_st.csv')

    df_total_hh_worked_st = pd.DataFrame(total_hh_worked_st)
    df_total_hh_worked_st.to_csv('df_total_hh_worked_st.csv')

    df_total_persons_worked_st = pd.DataFrame(total_persons_worked_st)
    df_total_persons_worked_st.to_csv('df_total_persons_worked_st.csv')'''


    # district wise remaining indicators
    #Total households completed person-days in range
    total_hh_completed_person_days_dt=[]
    for i in year_slct:    
        for l in total_hh:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_district()

            driver.find_element_by_id('TxtBox1').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox1')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_completed_person_days_dt.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total workers employed in age group
    total_workers_employed_dt=[]
    for i in year_slct:    
        for l in total_worker_age:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_district()

            driver.find_element_by_id('TxtBox9').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox9')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_workers_employed_dt.append(table)
            driver.find_element_by_id("BtnBack").click()

    #Total_hh_demanded_work
    total_hh_demanded_work_dt=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_district()

            driver.find_element_by_id('TxtBox5').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox5')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_demanded_work_dt.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_persons_demanded_work
    total_persons_demanded_work_dt=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_district()

            driver.find_element_by_id('TxtBox6').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox6')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_persons_demanded_work_dt.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_hh_worked
    total_hh_worked_dt=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_district()

            driver.find_element_by_id('TxtBox7').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox7')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_worked_dt.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_persons_worked
    total_persons_worked_dt=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_district()

            driver.find_element_by_id('TxtBox8').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox8')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_persons_worked_tt.append(table)
            driver.find_element_by_id("BtnBack").click()

    '''df_total_hh_completed_person_days_dt = pd.DataFrame(total_hh_completed_person_days_dt)
    df_total_hh_completed_person_days_dt.to_csv('df_total_hh_completed_person_days_dt.csv') 

    df_total_workers_employed_dt = pd.DataFrame(total_workers_employed_dt)
    df_total_workers_employed_dt.to_csv('df_total_workers_employed_dt.csv')

    df_total_hh_demanded_work_dt = pd.DataFrame(total_hh_demanded_work_dt)
    df_total_hh_demanded_work_dt.to_csv('df_total_hh_demanded_work_dt.csv')

    df_total_persons_demanded_work_dt = pd.DataFrame(total_persons_demanded_work_dt)
    df_total_persons_demanded_work_dt.to_csv('df_total_persons_demanded_work_dt.csv')

    df_total_hh_worked_dt = pd.DataFrame(total_hh_worked_dt)
    df_total_hh_worked_dt.to_csv('df_total_hh_worked_dt.csv')

    df_total_persons_worked_dt = pd.DataFrame(total_persons_worked_dt)
    df_total_persons_worked_dt.to_csv('df_total_persons_worked_dt.csv')
    '''
    # Block wise remaining indicators
    #Total households completed person-days in range
    total_hh_completed_person_days_bl=[]
    for i in year_slct:    
        for l in total_hh:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_block()

            driver.find_element_by_id('TxtBox1').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox1')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_completed_person_days_bl.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total workers employed in age group
    total_workers_employed_bl=[]
    for i in year_slct:    
        for l in total_worker_age:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_block()

            driver.find_element_by_id('TxtBox9').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox9')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_workers_employed_bl.append(table)
            driver.find_element_by_id("BtnBack").click()

    #Total_hh_demanded_work
    total_hh_demanded_work_bl=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_block()

            driver.find_element_by_id('TxtBox5').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox5')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_demanded_work_bl.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_persons_demanded_work
    total_persons_demanded_work_bl=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_block()

            driver.find_element_by_id('TxtBox6').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox6')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_persons_demanded_work_bl.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_hh_worked
    total_hh_worked_bl=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_block()

            driver.find_element_by_id('TxtBox7').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox7')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_hh_worked_bl.append(table)
            driver.find_element_by_id("BtnBack").click()

    #total_persons_worked
    total_persons_worked_bl=[]
    for i in year_slct:    
        for l in months:

            year_element = driver.find_element_by_id("DdlstFinYear")
            year_drp = Select(year_element)
            year_drp.select_by_visible_text(i)

            slct_block()

            driver.find_element_by_id('TxtBox8').click()

            drp_ele = driver.find_element_by_id('DdlstTxtBox8')
            drp = Select(drp_ele)
            drp.select_by_visible_text(l)

            driver.find_element_by_id("viewDummy").click()
            time.sleep(2) 

            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            div=soup.select_one("div#content")
            table=pd.read_html(str(div))
            total_persons_worked_bl.append(table)
            driver.find_element_by_id("BtnBack").click()

    driver.quit()

    '''df_total_hh_completed_person_days_bl = pd.DataFrame(total_hh_completed_person_days_bl)
    df_total_hh_completed_person_days_bl.to_csv('df_total_hh_completed_person_days_bl.csv') 

    df_total_workers_employed_bl = pd.DataFrame(total_workers_employed_bl)
    df_total_workers_employed_bl.to_csv('df_total_workers_employed_bl.csv')

    df_total_hh_demanded_work_bl = pd.DataFrame(total_hh_demanded_work_bl)
    df_total_hh_demanded_work_bl.to_csv('df_total_hh_demanded_work_bl.csv')

    df_total_persons_demanded_work_bl = pd.DataFrame(total_persons_demanded_work_bl)
    df_total_persons_demanded_work_bl.to_csv('df_total_persons_demanded_work_bl.csv')

    df_total_hh_worked_bl = pd.DataFrame(total_hh_worked_bl)
    df_total_hh_worked_bl.to_csv('df_total_hh_worked_bl.csv')

    df_total_persons_worked_bl = pd.DataFrame(total_persons_worked_bl)
    df_total_persons_worked_bl.to_csv('df_total_persons_worked_bl.csv')'''

    return df_state
    pkl_df_state = "df_state.pkl"
    path = os.path.join(download_dir, pkl_df_state)
    df_state.to_pickle(path)

    return df_district
    pkl_df_district = "df_district.pkl"
    path = os.path.join(download_dir, pkl_df_district)
    df_district.to_pickle(path)

    return df_block
    pkl_df_block = "df_block.pkl"
    path = os.path.join(download_dir, pkl_df_block)
    df_block.to_pickle(path)

    #state-level for remaining indicators
    return df_total_hh_completed_person_days_st
    pkl_df_total_hh_completed_person_days_st = "df_total_hh_completed_person_days_st.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_completed_person_days_st)
    df_total_hh_completed_person_days_st.to_pickle(path)

    return df_total_workers_employed_st
    pkl_df_total_workers_employed_st = "df_total_workers_employed_st.pkl"
    path = os.path.join(download_dir, pkl_df_total_workers_employed_st)
    df_total_workers_employed_st.to_pickle(path)

    return df_total_hh_demanded_work_st
    pkl_df_total_hh_demanded_work_st = "df_total_hh_demanded_work_st.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_demanded_work_st)
    df_total_hh_demanded_work_st.to_pickle(path)

    return df_total_persons_demanded_work_st
    pkl_df_total_persons_demanded_work_st = "df_total_persons_demanded_work_st.pkl"
    path = os.path.join(download_dir, pkl_df_total_persons_demanded_work_st)
    df_total_persons_demanded_work_st.to_pickle(path)

    return df_total_hh_worked_st
    pkl_df_total_hh_worked_st = "df_total_hh_worked_st.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_worked_st)
    df_total_hh_worked_st.to_pickle(path)

    return df_total_persons_worked_st
    pkl_df_total_persons_worked_st = "df_total_persons_worked_st.pkl"
    path = os.path.join(download_dir, pkl_df_total_persons_worked_st)
    df_total_persons_worked_st.to_pickle(path)

    #district-level for remaining indicators
    return df_total_hh_completed_person_days_dt
    pkl_df_total_hh_completed_person_days_dt = "df_total_hh_completed_person_days_dt.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_completed_person_days_dt)
    df_total_hh_completed_person_days_dt.to_pickle(path)

    return df_total_workers_employed_dt
    pkl_df_total_workers_employed_dt = "df_total_workers_employed_dt.pkl"
    path = os.path.join(download_dir, pkl_df_total_workers_employed_dt)
    df_total_workers_employed_dt.to_pickle(path)

    return df_total_hh_demanded_work_dt
    pkl_df_total_hh_demanded_work_dt = "df_total_hh_demanded_work_dt.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_demanded_work_dt)
    df_total_hh_demanded_work_dt.to_pickle(path)

    return df_total_persons_demanded_work_dt
    pkl_df_total_persons_demanded_work_dt = "df_total_persons_demanded_work_dt.pkl"
    path = os.path.join(download_dir, pkl_df_total_persons_demanded_work_dt)
    df_total_persons_demanded_work_dt.to_pickle(path)

    return df_total_hh_worked_dt
    pkl_df_total_hh_worked_dt = "df_total_hh_worked_dt.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_worked_dt)
    df_total_hh_worked_dt.to_pickle(path)

    return df_total_persons_worked_dt
    pkl_df_total_persons_worked_dt = "df_total_persons_worked_dt.pkl"
    path = os.path.join(download_dir, pkl_df_total_persons_worked_dt)
    df_total_persons_worked_dt.to_pickle(path)

    #block-level for remaining indicators
    return df_total_hh_completed_person_days_bl
    pkl_df_total_hh_completed_person_days_bl = "df_total_hh_completed_person_days_bl.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_completed_person_days_bl)
    df_total_hh_completed_person_days_bl.to_pickle(path)

    return df_total_workers_employed_bl
    pkl_df_total_workers_employed_bl = "df_total_workers_employed_bl.pkl"
    path = os.path.join(download_dir, pkl_df_total_workers_employed_bl)
    df_total_workers_employed_bl.to_pickle(path)

    return df_total_hh_demanded_work_bl
    pkl_df_total_hh_demanded_work_bl = "df_total_hh_demanded_work_bl.pkl"
    path = os.path.join(download_dir, pkl_df_total_hh_demanded_work_bl)
    df_total_hh_demanded_work_bl.to_pickle(path)

    return df_total_persons_demanded_work_bl
    pkl_df_total_persons_demanded_work_bl = "df_total_persons_demanded_work_bl.pkl"
    path = os.path.join(download_dir,pkl_df_total_persons_demanded_work_bl )
    df_total_persons_demanded_work_bl.to_pickle(path)

    return df_total_hh_worked_bl
    pkl_df_total_hh_worked_bl = "df_total_hh_worked_bl.pkl"
    path = os.path.join(download_dir,pkl_df_total_hh_worked_bl )
    df_total_hh_worked_bl.to_pickle(path)

    return df_total_persons_worked_bl
    pkl_df_total_persons_worked_bl = "df_total_persons_worked_bl.pkl"
    path = os.path.join(download_dir,pkl_df_total_persons_worked_bl )
    df_total_persons_worked_bl.to_pickle(path)